import json
import frappe
from wafd_one.patches.v10_0_0_rc43.execute import _save_template, _invoice_with_tax_identity, LOGO
from wafd_one.patches.v10_0_0_rc42.execute import _final_undertaking_canvas

def _compact(title_en, title_ar, rows, extra=""):
    blocks=[{"id":"header","type":"html","x":34,"y":25,"w":726,"h":82,"html":f'<div style="border-bottom:1px solid #b79b55;padding-bottom:8px;text-align:center;"><img src="{LOGO}" style="position:absolute;right:0;top:0;width:70px;height:60px;object-fit:contain;"><b style="font-size:16px;">شركة وفد المدينة لخدمات الإعاشة</b><div style="font-size:9px;color:#777;">WAFD AL-MADINAH CATERING SERVICES</div><h2 style="margin:8px 0 0;">{title_ar}</h2><div style="font-size:10px;">{title_en}</div></div>'}]
    y=118
    html='<table style="width:100%;border-collapse:collapse;font-size:10px;direction:rtl;">'
    for a,b in rows: html+=f'<tr><td style="border:1px solid #ddd;padding:5px;background:#f5f5f5;width:24%;"><b>{a[0]}</b></td><td style="border:1px solid #ddd;padding:5px;width:26%;">{a[1]}</td><td style="border:1px solid #ddd;padding:5px;background:#f5f5f5;width:24%;"><b>{b[0]}</b></td><td style="border:1px solid #ddd;padding:5px;width:26%;">{b[1]}</td></tr>'
    html+='</table>'
    blocks.append({"id":"details","type":"html","x":34,"y":y,"w":726,"h":285,"html":html})
    blocks.append({"id":"extra","type":"html","x":34,"y":410,"w":726,"h":210,"html":extra})
    blocks.append({"id":"sign","type":"html","x":34,"y":640,"w":726,"h":90,"html":'<div style="display:flex;justify-content:space-between;font-size:10px;direction:rtl;"><div>إعداد / Prepared by<br><br>________________</div><div>مراجعة / Reviewed by<br><br>________________</div><div>اعتماد / Approved by<br><br>________________</div></div>'})
    blocks.append({"id":"footer","type":"html","x":34,"y":756,"w":726,"h":28,"html":'<div style="border-top:1px solid #b79b55;text-align:center;font-size:8px;padding-top:5px;direction:rtl;">0500336989 &nbsp; | &nbsp; www.wafdalmadinah.com &nbsp; | &nbsp; الرقم الضريبي: 314262038700003</div>'})
    return {"page":{"width":794,"height":1123,"background":"#fff"},"blocks":blocks}

def execute():
    if not frappe.db.exists("DocType","WAFD Document Template"): return
    _save_template("WAFD Invoice","الفاتورة الضريبية الاحترافية","Invoice",_invoice_with_tax_identity())
    undertaking = _final_undertaking_canvas()
    for block in undertaking.get("blocks", []):
        if block.get("id") == "signature_image_final":
            block["html"] = '{% if doc.include_signature %}{% set sig = doc.signature_image or template.signature %}{% if sig %}<div style="width:100%;height:100%;text-align:center;"><img src="{{ sig }}" alt="" style="max-width:100%;max-height:100%;object-fit:contain;"></div>{% endif %}{% endif %}'
        elif block.get("id") == "stamp_image_final":
            block["html"] = '{% if doc.include_stamp %}{% set seal = doc.company_stamp or template.stamp %}{% if seal %}<div style="width:100%;height:100%;text-align:center;"><img src="{{ seal }}" alt="" style="max-width:100%;max-height:100%;object-fit:contain;"></div>{% endif %}{% endif %}'
    _save_template("WAFD Hotel Undertaking","تعهد الفندق المستقل","Undertaking",undertaking)
    _save_template("WAFD Packaging Record","أمر التغليف","Other",_compact("PACKAGING ORDER","أمر التغليف",[(("المشروع / Project",'{{ doc.project or "" }}'),("دفعة الإنتاج / Production Batch",'{{ doc.production_batch or "" }}')),(('خطة الوجبة / Meal Plan','{{ doc.meal_plan or "" }}'),('تاريخ التغليف / Packaging Date','{{ frappe.utils.formatdate(doc.packaging_date) if doc.packaging_date else "" }}')),(('الكمية المخططة / Planned Qty','{{ doc.planned_quantity or 0 }}'),('الكمية المغلفة / Packed Qty','{{ doc.packed_quantity or 0 }}')),(('عدد الصناديق / Boxes','{{ doc.box_count or 0 }}'),('عدد السخانات / Hot Cabinets','{{ doc.hot_cabinet_count or 0 }}'))],'<div style="font-size:9px;line-height:1.35;direction:rtl;"><b>بيان التغليف:</b><pre style="white-space:pre-wrap;font-family:Arial;font-size:8px;">{{ doc.box_manifest or "" }}</pre><b>ملاحظات:</b> {{ doc.notes or "" }}</div>'))
    _save_template("WAFD Loading Record","أمر التحميل","Other",_compact("LOADING ORDER","أمر التحميل",[(("المشروع / Project",'{{ doc.project or "" }}'),("سجل التغليف / Packaging",'{{ doc.packaging_record or "" }}')),(('الفندق / Hotel','{{ doc.hotel or "" }}'),('وقت التحميل / Loading Time','{{ doc.loading_date or "" }}')),(('المركبة / Vehicle','{{ doc.vehicle or "" }}'),('السائق / Driver','{{ doc.driver or "" }}')),(('الكمية / Quantity','{{ doc.quantity or 0 }}'),('عدد الصناديق / Boxes','{{ doc.box_count or 0 }}')),(('عدد السخانات / Hot Cabinets','{{ doc.hot_cabinet_count or 0 }}'),('إجمالي السفندشات / Sandwiches','{{ doc.hot_cabinet_sandwich_total or 0 }}'))],'<div style="direction:rtl;font-size:10px;"><b>حالة التحميل:</b> {{ doc.status or "" }}<br><br><b>ملاحظات:</b> {{ doc.notes or "" }}</div>'))
    _save_template("WAFD Delivery Note","سند التسليم","Delivery",_compact("DELIVERY NOTE","سند التسليم",[(("المشروع / Project",'{{ doc.project or "" }}'),("رحلة التوصيل / Trip",'{{ doc.delivery_trip or "" }}')),(('الفندق / Hotel','{{ doc.hotel or "" }}'),('وقت التسليم / Delivery Time','{{ doc.delivery_time or "" }}')),(('المركبة / Vehicle','{{ doc.vehicle or "" }}'),('السائق / Driver','{{ doc.driver or "" }}')),(('الكمية المسلمة / Delivered Qty','{{ doc.delivered_quantity or 0 }}'),('عدد السخانات / Hot Cabinets','{{ doc.hot_cabinet_count or 0 }}'))],'<div style="direction:rtl;font-size:10px;"><b>اسم المستلم:</b> {{ doc.receiver_name or "" }} &nbsp;&nbsp; <b>الصفة:</b> {{ doc.receiver_title or "" }}<br><br><b>ملاحظات:</b> {{ doc.notes or "" }}</div>'))
    _save_template("WAFD Receiving Note","سند الاستلام","Delivery",_compact("RECEIVING NOTE","سند الاستلام",[(("المشروع / Project",'{{ doc.project or "" }}'),("سند التسليم / Delivery Note",'{{ doc.delivery_note or "" }}')),(('الفندق / Hotel','{{ doc.hotel or "" }}'),('وقت الاستلام / Receipt Time','{{ doc.receipt_time or "" }}')),(('الكمية المسلمة / Delivered Qty','{{ doc.delivered_quantity or 0 }}'),('الكمية المستلمة / Received Qty','{{ doc.received_quantity or 0 }}')),(('الكمية المرفوضة / Rejected Qty','{{ doc.rejected_quantity or 0 }}'),('حالة الوجبات / Condition','{{ doc.condition_status or "" }}'))],'<div style="direction:rtl;font-size:10px;"><b>اسم المستلم:</b> {{ doc.receiver_name or "" }} &nbsp;&nbsp; <b>الصفة:</b> {{ doc.receiver_title or "" }}<br><br><b>ملاحظات:</b> {{ doc.notes or "" }}</div>'))
    frappe.clear_cache()
