frappe.pages["wafd-delivery-supervisor"].on_page_load = function(wrapper) {
  const lang = localStorage.getItem("wafd_lang") || "ar";
  const ar = lang === "ar";
  const tr = (a,e) => ar ? a : e;
  const esc = (v) => frappe.utils.escape_html(String(v == null ? "" : v));
  const page = frappe.ui.make_app_page({parent:wrapper,title:tr("إدارة التوصيل","Delivery Management"),single_column:true});
  const $root = $(page.body);
  let data = {}, view = "current";
  const mealTimes = {"إفطار / Breakfast":"04:00","غداء / Lunch":"10:00","عشاء / Dinner":"17:00","إفطار صائم / Iftar Saim":"12:00"};
  const localValue = (v) => {const p=String(v||"").split("/").map(x=>x.trim());return p.length>1?(ar?p[0]:p[p.length-1]):String(v||"");};
  const status = (v) => localValue(v || "—");
  const destination = (row) => ar ? (row.destination_name || row.hotel || "—") : (row.destination_name_en || row.destination_name || row.hotel || "—");

  function renderShell(){
    page.set_title(tr("إدارة التوصيل","Delivery Management"));
    $root.attr("dir",ar?"rtl":"ltr").html(`<div class="wafd-delivery-board"><section class="wafd-delivery-hero"><div><small>WAFD ONE</small><h2>${esc(tr("خطة التوصيل اليومية","Daily Delivery Plan"))}</h2></div><div class="wafd-delivery-actions"><button class="primary" data-action="new">＋ ${esc(tr("إضافة رحلة","Add Delivery"))}</button><button data-action="location">＋ ${esc(tr("موقع أو فندق","Location or Hotel"))}</button></div></section><section class="wafd-delivery-summary"><div><b>${esc(data.summary?.current||0)}</b><small>${esc(tr("رحلات حالية","Current deliveries"))}</small></div><div><b>${esc(data.summary?.delivered||0)}</b><small>${esc(tr("تسليمات موثقة","Documented deliveries"))}</small></div></section><div class="wafd-delivery-tabs"><button data-view="current" class="${view==='current'?'is-active':''}">${esc(tr("الرحلات الحالية","Current"))}</button><button data-view="delivered" class="${view==='delivered'?'is-active':''}">${esc(tr("سجل التسليم","Delivery records"))}</button></div><div id="wafd-delivery-list" class="wafd-delivery-list"></div></div>`);
    renderList();
  }
  function renderList(){
    const rows=data[view]||[], $list=$root.find("#wafd-delivery-list");
    if(!rows.length)return $list.html(`<div class="wafd-delivery-empty">${esc(tr("لا توجد بيانات حالياً","No records currently"))}</div>`);
    $list.html(rows.map(row=>{const proof=row.proof||null;return `<article class="wafd-delivery-card"><div class="wafd-delivery-card-head"><div><h3>${esc(destination(row))}</h3><small>${esc(localValue(row.delivery_kind))} · ${esc(localValue(row.meal_type))}</small></div><span class="wafd-delivery-status">${esc(status(row.display_status))}</span></div><div class="wafd-delivery-info"><div><small>${esc(tr("التاريخ والوقت","Date & time"))}</small><b>${esc(frappe.datetime.str_to_user(row.planned_arrival)||row.trip_date)}</b></div><div><small>${esc(tr("السائق","Driver"))}</small><b>${esc(row.driver||"—")}</b></div><div><small>${esc(tr("المركبة","Vehicle"))}</small><b>${esc(row.vehicle||tr("اختياري","Optional"))}</b></div><div><small>${esc(tr("عدد الوجبات","Meals"))}</small><b>${Number(row.quantity)>0?esc(row.quantity):esc(tr("غير محدد","Not specified"))}</b></div></div><div class="wafd-delivery-card-actions">${row.destination_map_url?`<a href="${esc(row.destination_map_url)}" target="_blank" rel="noopener">${esc(tr("فتح الموقع","Open location"))}</a>`:""}${!proof&&row.trip_source==='خطة مشرف التوصيل / Delivery Supervisor Plan'&&row.status==='مخططة / Planned'?`<button data-cancel="${esc(row.name)}">${esc(tr("إلغاء","Cancel"))}</button>`:""}</div>${proof?`<div class="wafd-delivery-proof"><a href="${esc(proof.delivery_photo)}" target="_blank"><img src="${esc(proof.delivery_photo)}"></a><div><b>${esc(tr("تم التسليم","Delivered"))}: ${esc(frappe.datetime.str_to_user(proof.delivery_time))}</b><small>${esc(tr("المستلم","Receiver"))}: ${esc(proof.receiver_name||"—")}</small><small>${esc(tr("الموقع الفعلي","Actual location"))}: ${proof.latitude&&proof.longitude?`<a href="https://www.google.com/maps?q=${esc(proof.latitude)},${esc(proof.longitude)}" target="_blank">${esc(tr("عرض على الخريطة","View map"))}</a>`:esc(tr("غير متاح","Unavailable"))}</small></div></div>`:""}</article>`;}).join(""));
  }
  const optionRows=(rows,value,label,placeholder)=>`<option value="">${esc(placeholder)}</option>${rows.map(r=>`<option value="${esc(r[value])}">${esc(label(r))}</option>`).join("")}`;
  function openNew(){
    const d=new frappe.ui.Dialog({title:tr("إضافة رحلة توصيل","Add Delivery"),size:"large",fields:[{fieldname:"body",fieldtype:"HTML"}],primary_action_label:tr("إرسال إلى السائق","Assign to Driver"),primary_action:async()=>{const $p=d.fields_dict.body.$wrapper;const task={destination_type:$p.find("#ds-type").val(),destination:$p.find("#ds-destination").val(),meal_type:$p.find("#ds-meal").val(),delivery_time:$p.find("#ds-time").val(),driver:$p.find("#ds-driver").val(),vehicle:$p.find("#ds-vehicle").val(),quantity:$p.find("#ds-qty").val(),notes:$p.find("#ds-notes").val()};if(!task.destination||!task.driver)return frappe.msgprint(tr("اختر الوجهة والسائق","Choose destination and driver"));const r=await frappe.call({method:"wafd_one.delivery_supervisor.create_delivery_tasks",args:{delivery_date:$p.find("#ds-date").val(),tasks:JSON.stringify([task])},freeze:true,freeze_message:tr("جارٍ إرسال الرحلة للسائق…","Assigning delivery…")});if(r.message?.count){d.hide();frappe.show_alert({message:tr("تم إرسال الرحلة للسائق","Delivery assigned"),indicator:"green"},5);await load();}}});
    d.show();const $p=d.fields_dict.body.$wrapper;
    $p.html(`<div class="wafd-delivery-form"><label><span>${esc(tr("تاريخ التوصيل","Delivery date"))}</span><input id="ds-date" type="date" value="${esc(data.today)}"></label><div class="wafd-delivery-two"><label><span>${esc(tr("نوع الوجهة","Destination type"))}</span><select id="ds-type"><option value="hotel">${esc(tr("فندق","Hotel"))}</option><option value="location">${esc(tr("مسجد، حرم أو موقع","Mosque, Haram or location"))}</option></select></label><label><span>${esc(tr("ابحث عن الوجهة","Search destination"))}</span><input id="ds-search" class="wafd-destination-search" type="search" placeholder="${esc(tr("اكتب اسم الفندق أو الموقع","Type hotel or location name"))}"></label></div><label><span>${esc(tr("الوجهة","Destination"))}</span><select id="ds-destination"></select></label><div class="wafd-delivery-two"><label><span>${esc(tr("نوع الوجبة","Meal type"))}</span><select id="ds-meal">${Object.keys(mealTimes).map(x=>`<option value="${esc(x)}">${esc(localValue(x))}</option>`).join("")}</select></label><label><span>${esc(tr("وقت التوصيل","Delivery time"))}</span><input id="ds-time" type="time" value="04:00"></label></div><div class="wafd-delivery-two"><label><span>${esc(tr("السائق","Driver"))}</span><select id="ds-driver">${optionRows(data.drivers||[],"name",r=>r.display_name,tr("اختر السائق","Choose driver"))}</select></label><label><span>${esc(tr("المركبة (اختياري)","Vehicle (optional)"))}</span><select id="ds-vehicle">${optionRows(data.vehicles||[],"name",r=>r.plate_number||r.name,tr("بدون تحديد","Not specified"))}</select></label></div><label><span>${esc(tr("عدد الوجبات (اختياري)","Meal count (optional)"))}</span><input id="ds-qty" type="number" min="0" inputmode="numeric" placeholder="0"></label><label><span>${esc(tr("ملاحظات (اختياري)","Notes (optional)"))}</span><textarea id="ds-notes"></textarea></label><small class="wafd-delivery-help">${esc(tr("الأوقات الافتراضية: الإفطار 4 فجراً، الغداء 10 صباحاً، العشاء 5 عصراً، إفطار الصائم 12 ظهراً. ويمكن تعديل الوقت.","Defaults: breakfast 4:00, lunch 10:00, dinner 17:00, Iftar Saim 12:00. Time remains editable."))}</small></div>`);
    const refreshDestinations=()=>{const type=$p.find("#ds-type").val(),q=$p.find("#ds-search").val().trim().toLowerCase();const rows=(type==="hotel"?(data.hotels||[]):(data.locations||[])).filter(r=>{const s=`${r.hotel_name_ar||r.location_name_ar||""} ${r.hotel_name_en||r.location_name_en||""}`.toLowerCase();return !q||s.includes(q);});$p.find("#ds-destination").html(optionRows(rows,"name",r=>ar?(r.hotel_name_ar||r.location_name_ar||r.name):(r.hotel_name_en||r.location_name_en||r.hotel_name_ar||r.location_name_ar||r.name),tr("اختر الوجهة","Choose destination")));};
    refreshDestinations();$p.on("change","#ds-type",refreshDestinations);$p.on("input","#ds-search",refreshDestinations);$p.on("change","#ds-meal",function(){$p.find("#ds-time").val(mealTimes[this.value]||"12:00");});
  }
  function openLocation(){
    const types={"فندق / Hotel":"hotel","مسجد أو حرم / Mosque or Haram":"mosque","موقع إفطار صائم / Iftar Site":"iftar","جهة أو شركة / Entity or Company":"entity","موقع آخر / Other Location":"other"};
    const d=new frappe.ui.Dialog({title:tr("إضافة موقع أو فندق","Add Location or Hotel"),fields:[{fieldname:"destination_type_label",fieldtype:"Select",label:tr("النوع","Type"),options:Object.keys(types).map(localValue).join("\n"),default:localValue("فندق / Hotel"),reqd:1},{fieldname:"name_ar",fieldtype:"Data",label:tr("الاسم بالعربي","Arabic name"),reqd:1},{fieldname:"name_en",fieldtype:"Data",label:tr("الاسم بالإنجليزي (اختياري)","English name (optional)")},{fieldname:"map_url",fieldtype:"Data",label:tr("رابط الموقع","Map link")},{fieldname:"address",fieldtype:"Small Text",label:tr("العنوان","Address")}],primary_action_label:tr("حفظ","Save"),primary_action:async v=>{const selected=Object.keys(types).find(x=>localValue(x)===v.destination_type_label);const args={...v,destination_type:types[selected]};delete args.destination_type_label;const r=await frappe.call({method:"wafd_one.delivery_supervisor.add_delivery_destination",args,freeze:true});if(r.message?.name){d.hide();frappe.show_alert({message:tr("تم حفظ الوجهة","Destination saved"),indicator:"green"},4);await load();}}});d.show();
  }
  async function load(){const r=await frappe.call({method:"wafd_one.delivery_supervisor.get_delivery_board",freeze:true});data=r.message||{};renderShell();runRequestedAction();}
  function runRequestedAction(){const action=localStorage.getItem("wafd_delivery_action");if(!action)return;localStorage.removeItem("wafd_delivery_action");if(action==="new")openNew();if(action==="delivered"){view="delivered";renderShell();}if(action==="locations")openLocation();}
  $root.on("click","[data-action='new']",openNew);$root.on("click","[data-action='location']",openLocation);$root.on("click","[data-view]",function(){view=$(this).data("view");renderShell();});$root.on("click","[data-cancel]",function(){const name=$(this).data("cancel");frappe.confirm(tr("إلغاء هذه الرحلة؟","Cancel this delivery?"),async()=>{await frappe.call({method:"wafd_one.delivery_supervisor.cancel_planned_trip",args:{trip_name:name},freeze:true});await load();});});
  wrapper.wafdDeliveryLoad=load;load();
};
frappe.pages["wafd-delivery-supervisor"].on_page_show=function(wrapper){wrapper.wafdDeliveryLoad?.();};
