frappe.pages["wafd-delivery-supervisor"].on_page_load = function(wrapper) {
  const lang = localStorage.getItem("wafd_lang") || "ar";
  const ar = lang === "ar";
  const tr = (a,e) => ar ? a : e;
  const esc = (v) => frappe.utils.escape_html(String(v == null ? "" : v));
  const page = frappe.ui.make_app_page({parent:wrapper,title:tr("إدارة التوصيل","Delivery Management"),single_column:true});
  const $root = $(page.body);
  let data = {}, view = "current";
  const mealTimes = {"إفطار / Breakfast":"04:00","غداء / Lunch":"10:00","عشاء / Dinner":"17:00","إفطار صائم / Iftar Saim":"12:00"};
  const localValue = (v) => {const p=String(v||"").split("/").map(x=>x.trim());return p.length>1?(ar?p[0]:p[p.length-1]):String(v||"");};
  const status = (v) => localValue(v || "—");
  const destination = (row) => ar ? (row.destination_name || row.hotel || "—") : (row.destination_name_en || row.destination_name || row.hotel || "—");
  const findTrip = (name) => [...(data.current||[]),...(data.delivered||[])].find(row=>row.name===name);
  const enhanceTripCards = () => {
    const $heroActions=$root.find(".wafd-delivery-actions");
    if($heroActions.length&&!$heroActions.find("[data-action='recurring']").length)$heroActions.append(`<button data-action="recurring">＋ ${esc(tr("جدولة عدة أيام","Multi-day schedule"))}</button>`);
    $root.find(".wafd-delivery-card").each(function(){
      const $card=$(this);if($card.hasClass("wafd-card-managed"))return;
      const name=String($card.find("[data-share]").data("share")||""),row=findTrip(name);if(!row)return;
      $card.addClass("wafd-card-managed");const $actions=$card.find(".wafd-delivery-card-actions");
      $actions.find("[data-share]").text(`♙ ${tr("تحديد المستفيد","Assign beneficiary")}`);
      if(row.trip_source==="خطة مشرف التوصيل / Delivery Supervisor Plan"&&row.status==="مخططة / Planned"){
        $actions.append(`<button data-edit-trip="${esc(name)}">✎ ${esc(tr("تعديل الطلب","Edit delivery"))}</button>`);
        $actions.find("[data-cancel]").text(tr("حذف الطلب","Delete delivery"));
      }else if(row.proof){
        $actions.append(`<button data-archive-trip="${esc(name)}">${esc(tr("حذف من الشاشة","Remove from screen"))}</button>`);
      }
    });
  };
  new MutationObserver(enhanceTripCards).observe($root[0],{childList:true,subtree:true});

  function renderShell(){
    if(!document.getElementById("wafd-rc275-styles"))$("<style id='wafd-rc275-styles'>.wafd-recurring-grid{display:grid;gap:8px;margin-top:9px}.wafd-recurring-meal{display:grid!important;grid-template-columns:28px 1fr 125px 130px;align-items:center;gap:8px;padding:9px;border:1px solid #e5dece;border-radius:12px}.wafd-recurring-meal input{margin:0!important}.wafd-native-date{direction:ltr!important;text-align:left!important;unicode-bidi:isolate!important}.wafd-destination-manager{display:grid;gap:10px}.wafd-destination-toolbar{display:grid;grid-template-columns:1fr 150px;gap:8px}.wafd-destination-row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:12px;border:1px solid #e5dece;border-radius:13px}.wafd-destination-row small{display:block;color:#777b82}.wafd-destination-row button{border:1px solid #d7cbb4;background:#fff;border-radius:9px;padding:6px 9px;margin-inline-start:5px}.wafd-destination-row .danger{color:#922f2f}@media(max-width:650px){.wafd-recurring-meal{grid-template-columns:28px 1fr}.wafd-recurring-meal input[type=time],.wafd-recurring-meal input[type=number]{grid-column:2}.wafd-destination-toolbar{grid-template-columns:1fr}}</style>").appendTo(document.head);
    page.set_title(tr("إدارة التوصيل","Delivery Management"));
    if(!document.getElementById("wafd-date-direction-fix"))$("<style id='wafd-date-direction-fix'>.modal-dialog input[type=date]{direction:ltr!important;text-align:left!important;unicode-bidi:isolate!important;font-variant-numeric:tabular-nums}</style>").appendTo(document.head);
    if(!document.getElementById("wafd-share-styles"))$("<style id='wafd-share-styles'>.wafd-share-list{display:grid;gap:9px;margin-top:14px}.wafd-share-list>div{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px;border:1px solid #e6dfd2;border-radius:12px}.wafd-share-list span,.wafd-share-list small{display:block}.wafd-share-list small{color:#777b82}.wafd-share-list button{border:1px solid #d8cdb7;background:#fff;color:#8b2c2c;border-radius:9px;padding:6px 10px}.wafd-viewer-help{display:block;color:#777b82;line-height:1.7;margin:8px 0}.wafd-viewer-select{width:100%;height:46px;border:1px solid #ded7c9;border-radius:11px;padding:8px;background:#faf9f6}</style>").appendTo(document.head);
    $root.attr("dir",ar?"rtl":"ltr").html(`<div class="wafd-delivery-board"><section class="wafd-delivery-hero"><div><small>WAFD ONE</small><h2>${esc(tr("خطة التوصيل اليومية","Daily Delivery Plan"))}</h2></div><div class="wafd-delivery-actions"><button class="primary" data-action="new">＋ ${esc(tr("إضافة رحلة","Add Delivery"))}</button><button data-action="location">＋ ${esc(tr("موقع أو فندق","Location or Hotel"))}</button></div></section><section class="wafd-delivery-summary"><div><b>${esc(data.summary?.current||0)}</b><small>${esc(tr("رحلات حالية","Current deliveries"))}</small></div><div><b>${esc(data.summary?.delivered||0)}</b><small>${esc(tr("تسليمات موثقة","Documented deliveries"))}</small></div></section><div class="wafd-delivery-tabs"><button data-view="current" class="${view==='current'?'is-active':''}">${esc(tr("الرحلات الحالية","Current"))}</button><button data-view="delivered" class="${view==='delivered'?'is-active':''}">${esc(tr("سجل التسليم","Delivery records"))}</button></div><div id="wafd-delivery-list" class="wafd-delivery-list"></div></div>`);
    renderList();
  }
  function renderList(){
    const rows=data[view]||[], $list=$root.find("#wafd-delivery-list");
    if(!rows.length)return $list.html(`<div class="wafd-delivery-empty">${esc(tr("لا توجد بيانات حالياً","No records currently"))}</div>`);
    $list.html(rows.map(row=>{const proof=row.proof||null;return `<article class="wafd-delivery-card"><div class="wafd-delivery-card-head"><div><h3>${esc(destination(row))}</h3><small>${esc(localValue(row.delivery_kind))} · ${esc(localValue(row.meal_type))}</small></div><span class="wafd-delivery-status">${esc(status(row.display_status))}</span></div><div class="wafd-delivery-info"><div><small>${esc(tr("التاريخ والوقت","Date & time"))}</small><b>${esc(frappe.datetime.str_to_user(row.planned_arrival)||row.trip_date)}</b></div><div><small>${esc(tr("السائق","Driver"))}</small><b>${esc(row.driver||"—")}</b></div><div><small>${esc(tr("المركبة","Vehicle"))}</small><b>${esc(row.vehicle||tr("اختياري","Optional"))}</b></div><div><small>${esc(tr("عدد الوجبات","Meals"))}</small><b>${Number(row.quantity)>0?esc(row.quantity):esc(tr("غير محدد","Not specified"))}</b></div></div><div class="wafd-delivery-card-actions"><button data-share="${esc(row.name)}">↗ ${esc(tr("مشاركة المتابعة","Share tracking"))}</button>${row.destination_map_url?`<a href="${esc(row.destination_map_url)}" target="_blank" rel="noopener">${esc(tr("فتح الموقع","Open location"))}</a>`:""}${!proof&&row.trip_source==='خطة مشرف التوصيل / Delivery Supervisor Plan'&&row.status==='مخططة / Planned'?`<button data-cancel="${esc(row.name)}">${esc(tr("إلغاء","Cancel"))}</button>`:""}</div>${proof?`<div class="wafd-delivery-proof"><a href="${esc(proof.delivery_photo)}" target="_blank"><img src="${esc(proof.delivery_photo)}"></a><div><b>${esc(tr("تم التسليم","Delivered"))}: ${esc(frappe.datetime.str_to_user(proof.delivery_time))}</b><small>${esc(tr("المستلم","Receiver"))}: ${esc(proof.receiver_name||"—")}</small><small>${esc(tr("الموقع الفعلي","Actual location"))}: ${proof.latitude&&proof.longitude?`<a href="https://www.google.com/maps?q=${esc(proof.latitude)},${esc(proof.longitude)}" target="_blank">${esc(tr("عرض على الخريطة","View map"))}</a>`:esc(tr("غير متاح","Unavailable"))}</small></div></div>`:""}</article>`;}).join(""));
  }
  const optionRows=(rows,value,label,placeholder)=>`<option value="">${esc(placeholder)}</option>${rows.map(r=>`<option value="${esc(r[value])}">${esc(label(r))}</option>`).join("")}`;
  function openRecurring(){
    const mealRows=Object.entries(mealTimes).map(([meal,time],index)=>`<label class="wafd-recurring-meal"><input type="checkbox" data-meal="${esc(meal)}" ${index<3?"checked":""}><b>${esc(localValue(meal))}</b><input type="time" data-meal-time="${esc(meal)}" value="${esc(time)}"><input type="number" data-meal-qty="${esc(meal)}" min="0" inputmode="numeric" placeholder="${esc(tr("عدد الوجبات","Meals"))}"></label>`).join("");
    const d=new frappe.ui.Dialog({title:tr("جدولة الفندق لعدة أيام","Schedule Multiple Days"),size:"large",fields:[{fieldname:"body",fieldtype:"HTML"}],primary_action_label:tr("إنشاء الجدول وإرساله للسائق","Create and assign schedule"),primary_action:async()=>{const $p=d.fields_dict.body.$wrapper,meals=[];$p.find("[data-meal]:checked").each(function(){const meal=$(this).data("meal");meals.push({meal_type:meal,delivery_time:$p.find(`[data-meal-time='${meal}']`).val(),quantity:$p.find(`[data-meal-qty='${meal}']`).val()});});if(!meals.length)return frappe.msgprint(tr("اختر وجبة واحدة على الأقل","Select at least one meal"));const r=await frappe.call({method:"wafd_one.delivery_supervisor.create_recurring_delivery_tasks",args:{start_date:$p.find("#dr-start").val(),end_date:$p.find("#dr-end").val(),destination_type:$p.find("#dr-type").val(),destination:$p.find("#dr-destination").val(),meals:JSON.stringify(meals),driver:$p.find("#dr-driver").val(),vehicle:$p.find("#dr-vehicle").val()},freeze:true,freeze_message:tr("جارٍ إنشاء جدول الرحلات…","Creating delivery schedule…")});if(r.message){d.hide();frappe.msgprint(`${esc(tr("تم إنشاء الرحلات","Deliveries created"))}: <b>${esc(r.message.count||0)}</b>${r.message.skipped_duplicates?`<br>${esc(tr("تم تجاوز المكرر","Duplicates skipped"))}: ${esc(r.message.skipped_duplicates)}`:""}`);await load();}}});
    d.show();const $p=d.fields_dict.body.$wrapper;$p.html(`<div class="wafd-delivery-form"><div class="wafd-delivery-two"><label><span>${esc(tr("من تاريخ","Start date"))}</span><input id="dr-start" type="date" value="${esc(data.today)}"></label><label><span>${esc(tr("إلى تاريخ","End date"))}</span><input id="dr-end" type="date" value="${esc(data.today)}"></label></div><div class="wafd-delivery-two"><label><span>${esc(tr("نوع الوجهة","Destination type"))}</span><select id="dr-type"><option value="hotel">${esc(tr("فندق","Hotel"))}</option><option value="location">${esc(tr("مسجد، حرم أو جهة","Mosque, Haram or entity"))}</option></select></label><label><span>${esc(tr("بحث","Search"))}</span><input id="dr-search" type="search" placeholder="${esc(tr("اكتب اسم الوجهة","Type destination name"))}"></label></div><label><span>${esc(tr("الفندق أو الجهة","Hotel or destination"))}</span><select id="dr-destination"></select></label><div><b>${esc(tr("اختر الوجبات والوقت والكمية","Select meals, time and quantity"))}</b><div class="wafd-recurring-grid">${mealRows}</div></div><div class="wafd-delivery-two"><label><span>${esc(tr("السائق","Driver"))}</span><select id="dr-driver">${optionRows(data.drivers||[],"name",r=>r.display_name,tr("اختر السائق","Choose driver"))}</select></label><label><span>${esc(tr("المركبة (اختياري)","Vehicle (optional)"))}</span><select id="dr-vehicle">${optionRows(data.vehicles||[],"name",r=>r.plate_number||r.name,tr("بدون تحديد","Not specified"))}</select></label></div><small class="wafd-delivery-help">${esc(tr("يُنشئ النظام رحلة لكل وجبة في كل يوم، مع منع الرحلات المكررة تلقائياً.","The system creates one trip per selected meal per day and skips duplicates."))}</small></div>`);
    const refresh=()=>{const type=$p.find("#dr-type").val(),q=$p.find("#dr-search").val().trim().toLowerCase(),rows=(type==="hotel"?(data.hotels||[]):(data.locations||[])).filter(r=>`${r.hotel_name_ar||r.location_name_ar||""} ${r.hotel_name_en||r.location_name_en||""}`.toLowerCase().includes(q));$p.find("#dr-destination").html(optionRows(rows,"name",r=>ar?(r.hotel_name_ar||r.location_name_ar||r.name):(r.hotel_name_en||r.location_name_en||r.hotel_name_ar||r.location_name_ar||r.name),tr("اختر الوجهة","Choose destination")));};refresh();$p.on("change","#dr-type",refresh);$p.on("input","#dr-search",refresh);$p.on("change","#dr-start",function(){if($p.find("#dr-end").val()<this.value)$p.find("#dr-end").val(this.value);});
  }
  function openEditTrip(tripName){
    const row=findTrip(tripName);if(!row)return;const originalType=row.hotel?"hotel":"location",originalDestination=row.hotel||row.delivery_location||"",planned=String(row.planned_arrival||""),originalTime=planned.length>=16?planned.slice(11,16):"12:00";
    const d=new frappe.ui.Dialog({title:tr("تعديل رحلة التوصيل","Edit Delivery"),size:"large",fields:[{fieldname:"body",fieldtype:"HTML"}],primary_action_label:tr("حفظ التعديل","Save changes"),primary_action:async()=>{const $p=d.fields_dict.body.$wrapper;await frappe.call({method:"wafd_one.delivery_supervisor.update_planned_trip",args:{trip_name:tripName,delivery_date:$p.find("#de-date").val(),delivery_time:$p.find("#de-time").val(),destination_type:$p.find("#de-type").val(),destination:$p.find("#de-destination").val(),meal_type:$p.find("#de-meal").val(),driver:$p.find("#de-driver").val(),vehicle:$p.find("#de-vehicle").val(),quantity:$p.find("#de-qty").val()},freeze:true});d.hide();frappe.show_alert({message:tr("تم تعديل الرحلة","Delivery updated"),indicator:"green"},4);await load();}});
    d.show();const $p=d.fields_dict.body.$wrapper;$p.html(`<div class="wafd-delivery-form"><div class="wafd-delivery-two"><label><span>${esc(tr("التاريخ","Date"))}</span><input id="de-date" type="date" value="${esc(row.trip_date||data.today)}"></label><label><span>${esc(tr("الوقت","Time"))}</span><input id="de-time" type="time" value="${esc(originalTime)}"></label></div><div class="wafd-delivery-two"><label><span>${esc(tr("نوع الوجهة","Destination type"))}</span><select id="de-type"><option value="hotel">${esc(tr("فندق","Hotel"))}</option><option value="location">${esc(tr("مسجد، حرم أو جهة","Mosque, Haram or entity"))}</option></select></label><label><span>${esc(tr("بحث","Search"))}</span><input id="de-search" type="search"></label></div><label><span>${esc(tr("الوجهة","Destination"))}</span><select id="de-destination"></select></label><div class="wafd-delivery-two"><label><span>${esc(tr("الوجبة","Meal"))}</span><select id="de-meal">${Object.keys(mealTimes).map(x=>`<option value="${esc(x)}">${esc(localValue(x))}</option>`).join("")}</select></label><label><span>${esc(tr("الكمية","Quantity"))}</span><input id="de-qty" type="number" min="0" value="${esc(row.quantity||0)}"></label></div><div class="wafd-delivery-two"><label><span>${esc(tr("السائق","Driver"))}</span><select id="de-driver">${optionRows(data.drivers||[],"name",r=>r.display_name,tr("اختر السائق","Choose driver"))}</select></label><label><span>${esc(tr("المركبة","Vehicle"))}</span><select id="de-vehicle">${optionRows(data.vehicles||[],"name",r=>r.plate_number||r.name,tr("بدون تحديد","Not specified"))}</select></label></div></div>`);
    $p.find("#de-type").val(originalType);$p.find("#de-meal").val(row.meal_type);$p.find("#de-driver").val(row.driver);$p.find("#de-vehicle").val(row.vehicle||"");const refresh=()=>{const type=$p.find("#de-type").val(),q=$p.find("#de-search").val().trim().toLowerCase(),rows=(type==="hotel"?(data.hotels||[]):(data.locations||[])).filter(r=>`${r.hotel_name_ar||r.location_name_ar||""} ${r.hotel_name_en||r.location_name_en||""}`.toLowerCase().includes(q));$p.find("#de-destination").html(optionRows(rows,"name",r=>ar?(r.hotel_name_ar||r.location_name_ar||r.name):(r.hotel_name_en||r.location_name_en||r.hotel_name_ar||r.location_name_ar||r.name),tr("اختر الوجهة","Choose destination")));if(type===originalType&&!q)$p.find("#de-destination").val(originalDestination);};refresh();$p.on("change","#de-type",refresh);$p.on("input","#de-search",refresh);
  }
  function openNew(){
    const d=new frappe.ui.Dialog({title:tr("إضافة رحلة توصيل","Add Delivery"),size:"large",fields:[{fieldname:"body",fieldtype:"HTML"}],primary_action_label:tr("إرسال إلى السائق","Assign to Driver"),primary_action:async()=>{const $p=d.fields_dict.body.$wrapper;const task={destination_type:$p.find("#ds-type").val(),destination:$p.find("#ds-destination").val(),meal_type:$p.find("#ds-meal").val(),delivery_time:$p.find("#ds-time").val(),driver:$p.find("#ds-driver").val(),vehicle:$p.find("#ds-vehicle").val(),quantity:$p.find("#ds-qty").val(),notes:$p.find("#ds-notes").val()};if(!task.destination||!task.driver)return frappe.msgprint(tr("اختر الوجهة والسائق","Choose destination and driver"));const r=await frappe.call({method:"wafd_one.delivery_supervisor.create_delivery_tasks",args:{delivery_date:$p.find("#ds-date").val(),tasks:JSON.stringify([task])},freeze:true,freeze_message:tr("جارٍ إرسال الرحلة للسائق…","Assigning delivery…")});if(r.message?.count){d.hide();frappe.show_alert({message:tr("تم إرسال الرحلة للسائق","Delivery assigned"),indicator:"green"},5);await load();}}});
    d.show();const $p=d.fields_dict.body.$wrapper;
    $p.html(`<div class="wafd-delivery-form"><label><span>${esc(tr("تاريخ التوصيل","Delivery date"))}</span><input id="ds-date" type="date" value="${esc(data.today)}"></label><div class="wafd-delivery-two"><label><span>${esc(tr("نوع الوجهة","Destination type"))}</span><select id="ds-type"><option value="hotel">${esc(tr("فندق","Hotel"))}</option><option value="location">${esc(tr("مسجد، حرم أو موقع","Mosque, Haram or location"))}</option></select></label><label><span>${esc(tr("ابحث عن الوجهة","Search destination"))}</span><input id="ds-search" class="wafd-destination-search" type="search" placeholder="${esc(tr("اكتب اسم الفندق أو الموقع","Type hotel or location name"))}"></label></div><label><span>${esc(tr("الوجهة","Destination"))}</span><select id="ds-destination"></select></label><div class="wafd-delivery-two"><label><span>${esc(tr("نوع الوجبة","Meal type"))}</span><select id="ds-meal">${Object.keys(mealTimes).map(x=>`<option value="${esc(x)}">${esc(localValue(x))}</option>`).join("")}</select></label><label><span>${esc(tr("وقت التوصيل","Delivery time"))}</span><input id="ds-time" type="time" value="04:00"></label></div><div class="wafd-delivery-two"><label><span>${esc(tr("السائق","Driver"))}</span><select id="ds-driver">${optionRows(data.drivers||[],"name",r=>r.display_name,tr("اختر السائق","Choose driver"))}</select></label><label><span>${esc(tr("المركبة (اختياري)","Vehicle (optional)"))}</span><select id="ds-vehicle">${optionRows(data.vehicles||[],"name",r=>r.plate_number||r.name,tr("بدون تحديد","Not specified"))}</select></label></div><label><span>${esc(tr("عدد الوجبات (اختياري)","Meal count (optional)"))}</span><input id="ds-qty" type="number" min="0" inputmode="numeric" placeholder="0"></label><label><span>${esc(tr("ملاحظات (اختياري)","Notes (optional)"))}</span><textarea id="ds-notes"></textarea></label><small class="wafd-delivery-help">${esc(tr("الأوقات الافتراضية: الإفطار 4 فجراً، الغداء 10 صباحاً، العشاء 5 عصراً، إفطار الصائم 12 ظهراً. ويمكن تعديل الوقت.","Defaults: breakfast 4:00, lunch 10:00, dinner 17:00, Iftar Saim 12:00. Time remains editable."))}</small></div>`);
    const refreshDestinations=()=>{const type=$p.find("#ds-type").val(),q=$p.find("#ds-search").val().trim().toLowerCase();const rows=(type==="hotel"?(data.hotels||[]):(data.locations||[])).filter(r=>{const s=`${r.hotel_name_ar||r.location_name_ar||""} ${r.hotel_name_en||r.location_name_en||""}`.toLowerCase();return !q||s.includes(q);});$p.find("#ds-destination").html(optionRows(rows,"name",r=>ar?(r.hotel_name_ar||r.location_name_ar||r.name):(r.hotel_name_en||r.location_name_en||r.hotel_name_ar||r.location_name_ar||r.name),tr("اختر الوجهة","Choose destination")));};
    refreshDestinations();$p.on("change","#ds-type",refreshDestinations);$p.on("input","#ds-search",refreshDestinations);$p.on("change","#ds-meal",function(){$p.find("#ds-time").val(mealTimes[this.value]||"12:00");});
  }
  function openNewLocation(){
    const types={"فندق / Hotel":"hotel","مسجد أو حرم / Mosque or Haram":"mosque","موقع إفطار صائم / Iftar Site":"iftar","جهة أو شركة / Entity or Company":"entity","موقع آخر / Other Location":"other"};
    const d=new frappe.ui.Dialog({title:tr("إضافة موقع أو فندق","Add Location or Hotel"),fields:[{fieldname:"destination_type_label",fieldtype:"Select",label:tr("النوع","Type"),options:Object.keys(types).map(localValue).join("\n"),default:localValue("فندق / Hotel"),reqd:1},{fieldname:"name_ar",fieldtype:"Data",label:tr("الاسم بالعربي","Arabic name"),reqd:1},{fieldname:"name_en",fieldtype:"Data",label:tr("الاسم بالإنجليزي (اختياري)","English name (optional)")},{fieldname:"map_url",fieldtype:"Data",label:tr("رابط الموقع","Map link")},{fieldname:"address",fieldtype:"Small Text",label:tr("العنوان","Address")}],primary_action_label:tr("حفظ","Save"),primary_action:async v=>{const selected=Object.keys(types).find(x=>localValue(x)===v.destination_type_label);const args={...v,destination_type:types[selected]};delete args.destination_type_label;const r=await frappe.call({method:"wafd_one.delivery_supervisor.add_delivery_destination",args,freeze:true});if(r.message?.name){d.hide();frappe.show_alert({message:tr("تم حفظ الوجهة","Destination saved"),indicator:"green"},4);await load();}}});d.show();
  }
  function openLocation(){
    const d=new frappe.ui.Dialog({title:tr("إدارة المواقع والفنادق","Manage Locations and Hotels"),size:"large",fields:[{fieldname:"body",fieldtype:"HTML"}]});d.show();const $p=d.fields_dict.body.$wrapper;$p.html(`<div class="wafd-destination-manager"><button class="btn btn-primary" data-dm-add>＋ ${esc(tr("إضافة موقع أو فندق","Add location or hotel"))}</button><div class="wafd-destination-toolbar"><input data-dm-search type="search" placeholder="${esc(tr("ابحث بالاسم","Search by name"))}"><select data-dm-type><option value="all">${esc(tr("الكل","All"))}</option><option value="hotel">${esc(tr("الفنادق","Hotels"))}</option><option value="location">${esc(tr("المواقع والجهات","Locations and entities"))}</option></select></div><div data-dm-list>${esc(tr("جارٍ التحميل…","Loading…"))}</div></div>`);
    let timer;const refresh=async()=>{const r=await frappe.call({method:"wafd_one.delivery_supervisor.search_delivery_destinations",args:{query:$p.find("[data-dm-search]").val(),destination_type:$p.find("[data-dm-type]").val()}}),rows=r.message||[];$p.find("[data-dm-list]").html(rows.length?rows.map(row=>`<div class="wafd-destination-row"><span><b>${esc(row.name_ar||row.name)}</b><small>${esc(row.name_en||"")} · ${esc(row.destination_type==="hotel"?tr("فندق","Hotel"):tr("موقع أو جهة","Location or entity"))} · ${esc(row.trip_count||0)} ${esc(tr("رحلة","trips"))}</small><small>${row.map_url?esc(tr("الموقع محفوظ","Map saved")):esc(tr("لا يوجد رابط موقع — سيستخدم بحث Google","No map link — Google search will be used"))}</small></span><span><button data-dm-edit="${esc(row.name)}" data-dm-kind="${esc(row.destination_type)}">${esc(tr("تعديل","Edit"))}</button><button class="danger" data-dm-remove="${esc(row.name)}" data-dm-kind="${esc(row.destination_type)}">${esc(tr("حذف من القائمة","Remove"))}</button></span></div>`).join(""):`<div class="wafd-delivery-empty">${esc(tr("لا توجد نتائج","No results"))}</div>`);$p.data("rows",rows);};
    refresh();$p.on("input","[data-dm-search]",()=>{clearTimeout(timer);timer=setTimeout(refresh,250)});$p.on("change","[data-dm-type]",refresh);$p.on("click","[data-dm-add]",openNewLocation);$p.on("click","[data-dm-edit]",function(){const name=$(this).data("dm-edit"),kind=$(this).data("dm-kind"),row=($p.data("rows")||[]).find(x=>x.name===name&&x.destination_type===kind);if(!row)return;const edit=new frappe.ui.Dialog({title:tr("تعديل الموقع","Edit destination"),fields:[{fieldname:"name_ar",fieldtype:"Data",label:tr("الاسم بالعربي","Arabic name"),default:row.name_ar,reqd:1},{fieldname:"name_en",fieldtype:"Data",label:tr("الاسم بالإنجليزي","English name"),default:row.name_en},{fieldname:"map_url",fieldtype:"Data",label:tr("رابط Google Maps","Google Maps link"),default:row.map_url},{fieldname:"address",fieldtype:"Small Text",label:tr("العنوان","Address"),default:row.address}],primary_action_label:tr("حفظ التعديل","Save changes"),primary_action:async values=>{await frappe.call({method:"wafd_one.delivery_supervisor.update_delivery_destination",args:{destination_type:kind,name,...values},freeze:true});edit.hide();await load();await refresh();}});edit.show();});$p.on("click","[data-dm-remove]",function(){const name=$(this).data("dm-remove"),kind=$(this).data("dm-kind");frappe.confirm(tr("سيختفي من الاختيارات الجديدة، مع بقاء سجلات التسليم السابقة. متابعة؟","It will disappear from new choices while delivery history remains. Continue?"),async()=>{await frappe.call({method:"wafd_one.delivery_supervisor.remove_delivery_destination",args:{destination_type:kind,name},freeze:true});await load();await refresh();});});
  }
  async function openShare(tripName){
    const viewersResponse=await frappe.call({method:"wafd_one.delivery_tracking.list_delivery_viewers"});
    const viewers=viewersResponse.message||[];
    const d=new frappe.ui.Dialog({title:tr("تحديد المستفيد","Assign Beneficiary"),fields:[{fieldname:"viewer_html",fieldtype:"HTML"},{fieldname:"existing",fieldtype:"HTML"}],primary_action_label:tr("إسناد شاشة التسليم","Assign delivery screen"),primary_action:async()=>{const viewer=d.fields_dict.viewer_html.$wrapper.find("select").val();if(!viewer)return frappe.msgprint(tr("اختر المستفيد أولاً. أضفه من إدارة الموظفين إذا لم يظهر.","Choose a beneficiary. Add the account in Employee Management if it is missing."));await frappe.call({method:"wafd_one.delivery_tracking.assign_delivery_viewer",args:{trip_name:tripName,viewer_user:viewer},freeze:true});frappe.show_alert({message:tr("تم إسناد بيانات التسليم للمستفيد","Delivery data assigned to beneficiary"),indicator:"green"},4);await refreshAssignments();}});
    const options=viewers.map(v=>`<option value="${esc(v.name)}">${esc(v.display_name)} — ${esc(v.email||v.name)}</option>`).join("");
    d.show();d.fields_dict.viewer_html.$wrapper.html(`<small class="wafd-viewer-help">${esc(tr("يظهر هنا فقط من لديه مهمة «متابعة بيانات التسليم» في إدارة الموظفين. يدخل المستفيد ببريده وكلمة مروره ويشاهد الرحلات المسندة إليه فقط.","Only accounts with the Delivery Data task appear here. The beneficiary signs in and sees assigned deliveries only."))}</small><select class="wafd-viewer-select"><option value="">${esc(viewers.length?tr("اختر اسم المستفيد","Choose beneficiary"):tr("لا توجد حسابات مستفيدين — أضفها من إدارة الموظفين","No beneficiary accounts — add one in Employee Management"))}</option>${options}</select>`);
    const refreshAssignments=async()=>{const r=await frappe.call({method:"wafd_one.delivery_tracking.get_trip_viewers",args:{trip_name:tripName}}),rows=r.message||[];d.fields_dict.existing.$wrapper.html(`<div class="wafd-share-list"><b>${esc(tr("المستفيدون المصرح لهم","Assigned beneficiaries"))}</b>${rows.length?rows.map(s=>`<div><span><strong>${esc(s.viewer_name)}</strong><small dir="ltr">${esc(s.viewer_user)}</small></span><button data-remove-viewer="${esc(s.name)}">${esc(tr("إزالة","Remove"))}</button></div>`).join(""):`<small>${esc(tr("لم يتم تحديد مستفيد لهذه الرحلة","No beneficiary is assigned to this delivery"))}</small>`}</div>`);};
    await refreshAssignments();d.fields_dict.existing.$wrapper.on("click","[data-remove-viewer]",async function(){await frappe.call({method:"wafd_one.delivery_tracking.remove_delivery_viewer",args:{share_name:$(this).data("remove-viewer")},freeze:true});await refreshAssignments();});
  }
  async function load(){const r=await frappe.call({method:"wafd_one.delivery_supervisor.get_delivery_board",freeze:true});data=r.message||{};renderShell();runRequestedAction();}
  function runRequestedAction(){const action=localStorage.getItem("wafd_delivery_action");if(!action)return;localStorage.removeItem("wafd_delivery_action");if(action==="new")openNew();if(action==="delivered"){view="delivered";renderShell();}if(action==="locations")openLocation();}
  $root.on("click","[data-action='new']",openNew);$root.on("click","[data-action='location']",openLocation);$root.on("click","[data-view]",function(){view=$(this).data("view");renderShell();});$root.on("click","[data-cancel]",function(){const name=$(this).data("cancel");frappe.confirm(tr("إلغاء هذه الرحلة؟","Cancel this delivery?"),async()=>{await frappe.call({method:"wafd_one.delivery_supervisor.cancel_planned_trip",args:{trip_name:name},freeze:true});await load();});});$root.on("click","[data-share]",function(){openShare($(this).data("share"));});$(document).on("click","[data-copy-new]",function(){navigator.clipboard?.writeText($(this).data("copy-new"));frappe.show_alert({message:tr("تم نسخ الرابط","Link copied"),indicator:"green"},3);});
  $root.on("click","[data-action='recurring']",openRecurring);
  $root.on("click","[data-edit-trip]",function(){openEditTrip($(this).data("edit-trip"));});
  $root.on("click","[data-archive-trip]",function(){const name=$(this).data("archive-trip");frappe.confirm(tr("سيختفي السجل من شاشة التوصيل مع بقاء صورة التسليم والتدقيق. متابعة؟","The record will be hidden while its proof and audit remain. Continue?"),async()=>{await frappe.call({method:"wafd_one.delivery_supervisor.archive_delivery_trip",args:{trip_name:name},freeze:true});await load();});});
  wrapper.wafdDeliveryLoad=load;load();
};
frappe.pages["wafd-delivery-supervisor"].on_page_show=function(wrapper){wrapper.wafdDeliveryLoad?.();};
