app_name = "wafd_one"
app_title = "WAFD ONE"
app_publisher = "Wafd Almadinah"
app_description = "Catering and delivery operations for ERPNext"
app_email = "wafd.almadinah@gmail.com"
app_license = "proprietary"
after_install = "wafd_one.install.after_install"
