app_name = "wafd_one"
app_title = "WAFD ONE"
app_publisher = "Wafd Almadinah"
app_description = "Catering, projects, fleet and proof-of-delivery operations"
app_email = "wafd.almadinah@gmail.com"
app_license = "proprietary"
