"""Versioned market-reference catalog.

This catalog is a dated discovery snapshot, not a claim that any commercial
booking platform exposes a complete or permanently stable inventory.
"""

HOTEL_DISCOVERY_SNAPSHOT = [
    # Names additionally observed on major booking platforms / property sites.
    {"hotel_name":"ذا بيلتمور المدينة","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com / property listing snapshot","source_url":"https://www.booking.com/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق فيو المدينة","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/landmark/sa/the-mosque-of-the-prophet-mohammad.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق فالي المدينة VALY Al-Madinah","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/region/sa/al-madinah.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق مسك البلد Mysk Al Balad","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق ماين طيبة Maien Taiba","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/city/sa/medina.de.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق أنكيرا باي كونتيننت Ancyra Hotel by Continent","district":"المدينة المنورة","zone_type":"خارج المنطقة المركزية / Outside Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/city/sa/medina.de.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق بنينسولا وورث Peninsula Worth Hotel","district":"المدينة المنورة","zone_type":"خارج المنطقة المركزية / Outside Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/budget/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"مكارم برج المدينة Makarem Burj Al Madinah","district":"المدينة المنورة","zone_type":"خارج المنطقة المركزية / Outside Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/budget/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"جادة ريزيدنس Jadah Residence by CH","district":"المدينة المنورة","zone_type":"خارج المنطقة المركزية / Outside Central Zone","property_type":"شقق مخدومة / Serviced Apartments","source_authority":"Booking.com","source_url":"https://www.booking.com/budget/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق رؤى الأندلس البلاتيني Roaa Alandalus Platinum","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com / Agoda","source_url":"https://www.booking.com/city/sa/medina.nl.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"منازل الصفية Manazel AlSafiyah Hotel","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/city/sa/medina.nl.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"جولدن توليب الشاكرين Golden Tulip Al Shakreen","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com / Agoda","source_url":"https://www.agoda.com/hotels-near-al-masjid-an-nabawi/attractions/medina-sa.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"نُسك المدينة Nusk Al Madinah","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/city/sa/medina.de.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"رؤى الهجرة Rua Al Hijrah Hotel","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Agoda","source_url":"https://www.agoda.com/hotels-near-al-masjid-an-nabawi/attractions/medina-sa.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"إيلاف التقوى Elaf Al Taqwa Hotel","district":"المنطقة المركزية","zone_type":"المنطقة المركزية / Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"فندق إم بلاتينيوم M Platinum Hotel","district":"المدينة المنورة","zone_type":"خارج المنطقة المركزية / Outside Central Zone","property_type":"فندق / Hotel","source_authority":"Agoda","source_url":"https://www.agoda.com/m-platinum-hotel/hotel/medina-sa.html","verification_status":"يحتاج مراجعة / Needs Review"},
    {"hotel_name":"ميلينيوم مطار المدينة Millennium Madinah Airport","district":"المطار","zone_type":"خارج المنطقة المركزية / Outside Central Zone","property_type":"فندق / Hotel","source_authority":"Booking.com","source_url":"https://www.booking.com/region/sa/al-madinah.en-gb.html","verification_status":"يحتاج مراجعة / Needs Review"},
]

# Online retail observations are benchmarks only. Supplier invoices/quotes take
# precedence in operational costing.
INGREDIENT_PRICE_BENCHMARKS = [
    {"ingredient":"أرز بسمتي","source_name":"Carrefour KSA","source_url":"https://www.carrefourksa.com/mafsau/en/c/promo-ksa-weekly-offers-a","observed_on":"2026-07-19","pack_quantity":10,"pack_uom":"كجم / Kg","pack_price":69.99},
    {"ingredient":"أرز مصري","source_name":"Carrefour KSA market benchmark","source_url":"https://www.carrefourksa.com/mafsau/en","observed_on":"2026-07-19","pack_quantity":5,"pack_uom":"كجم / Kg","pack_price":32.50},
    {"ingredient":"صدور دجاج","source_name":"Carrefour KSA - Sadia","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":1,"pack_uom":"كجم / Kg","pack_price":21.99},
    {"ingredient":"دجاج كامل مبرد","source_name":"Carrefour KSA - Entaj","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-best-dealss","observed_on":"2026-07-19","pack_quantity":1.1,"pack_uom":"كجم / Kg","pack_price":20.25},
    {"ingredient":"زيت نباتي","source_name":"Carrefour KSA - Nakheel twin pack","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":3,"pack_uom":"لتر / Liter","pack_price":25.99},
    {"ingredient":"بطاطس","source_name":"Carrefour KSA","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":1,"pack_uom":"كجم / Kg","pack_price":3.99},
    {"ingredient":"بصل","source_name":"Carrefour KSA","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":1.4,"pack_uom":"كجم / Kg","pack_price":3.99},
    {"ingredient":"ثوم","source_name":"Carrefour KSA","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":200,"pack_uom":"جرام / Gram","pack_price":1.99},
    {"ingredient":"باذنجان","source_name":"Carrefour KSA","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":1,"pack_uom":"كجم / Kg","pack_price":4.99},
    {"ingredient":"تفاح","source_name":"Carrefour KSA - Royal Gala","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":1,"pack_uom":"كجم / Kg","pack_price":7.99},
    {"ingredient":"مكرونة","source_name":"Carrefour KSA - Goody","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":450,"pack_uom":"جرام / Gram","pack_price":4.00},
    {"ingredient":"بيض","source_name":"Carrefour KSA - 30 eggs","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-best-dealss","observed_on":"2026-07-19","pack_quantity":30,"pack_uom":"حبة / Piece","pack_price":19.47},
    {"ingredient":"جبنة كريمية","source_name":"Carrefour KSA - Kiri 800g","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-limited-todays","observed_on":"2026-07-19","pack_quantity":800,"pack_uom":"جرام / Gram","pack_price":37.99},
    {"ingredient":"معجون طماطم","source_name":"Carrefour KSA - Luna 135g x8","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-best-dealss","observed_on":"2026-07-19","pack_quantity":1080,"pack_uom":"جرام / Gram","pack_price":10.99},
    {"ingredient":"عصير 200 مل","source_name":"Carrefour KSA - Suntop 125ml x18 proxy","source_url":"https://www.carrefourksa.com/mafsau/en/c/ksa-best-dealss","observed_on":"2026-07-19","pack_quantity":18,"pack_uom":"حبة / Piece","pack_price":15.99},
]
