frappe.pages["wafd-delivery-report"].on_page_load = function(wrapper) {
  const roles=new Set(frappe.user_roles||[]);
  if(!["System Manager","WAFD Operations Manager","WAFD Delivery Supervisor"].some(role=>roles.has(role))){frappe.set_route("wafd-role-home");return;}
  const page=frappe.ui.make_app_page({parent:wrapper,title:"تقارير التوصيل",single_column:true});
  $(wrapper).addClass("wafd-delivery-report-page");
  const $root=$(page.body).attr("dir","rtl");let options={},scope="all";
  const esc=v=>frappe.utils.escape_html(String(v==null?"":v));
  $root.html(`<div class="wafd-report-shell"><section class="wafd-report-hero"><div><small>WAFD ONE</small><h2>تقارير التوصيل</h2><p>تقرير رسمي كامل المدة أو حسب الشركة أو الفندق</p></div><img class="wafd-report-logo" src="/assets/wafd_one/images/wafd-almadinah-official.png" alt="WAFD"></section><section class="wafd-report-panel"><div class="wafd-report-scope"><button class="is-active" data-scope="all">كامل المدة</button><button data-scope="company">حسب الشركة أو البعثة</button><button data-scope="hotel">حسب الفندق</button></div><div class="wafd-report-fields"><label data-company style="display:none"><span>الشركة أو البعثة أو الجهة</span><select id="wr-company"></select></label><label data-hotel style="display:none"><span>الفندق</span><select id="wr-hotel"></select></label><label><span>من تاريخ (اختياري)</span><input id="wr-from" type="date" dir="ltr" lang="en-CA"></label><label><span>إلى تاريخ (اختياري)</span><input id="wr-to" type="date" dir="ltr" lang="en-CA"></label></div><div class="wafd-report-actions"><button data-action="preview">معاينة</button><button class="primary" data-action="pdf">تنزيل PDF</button><button data-action="share">مشاركة</button><button data-action="print">طباعة</button></div><small class="wafd-report-note">ترك التاريخ فارغاً يعني كامل المدة. يحتوي التقرير على الوجبات، عدد السفندشات، السخانات، السائق، المركبة وبيانات التسليم.</small><div class="wafd-report-preview"><iframe title="معاينة تقرير التوصيل"></iframe></div></section></div>`);
  const query=(download,html=false)=>{const q=new URLSearchParams();const from=$root.find("#wr-from").val(),to=$root.find("#wr-to").val();if(from)q.set("from_date",from);if(to)q.set("to_date",to);if(scope==="company")q.set("contracting_entity",$root.find("#wr-company").val());if(scope==="hotel")q.set("hotel",$root.find("#wr-hotel").val());if(!html)q.set("download",download?"1":"0");return `/api/method/wafd_one.delivery_report.${html?"preview_delivery_report_html":"download_delivery_report_pdf"}?${q.toString()}`;};
  const validate=()=>{if(scope==="company"&&!$root.find("#wr-company").val()){frappe.msgprint("اختر الشركة أو البعثة أولاً");return false;}if(scope==="hotel"&&!$root.find("#wr-hotel").val()){frappe.msgprint("اختر الفندق أولاً");return false;}const from=$root.find("#wr-from").val(),to=$root.find("#wr-to").val();if(from&&to&&from>to){frappe.msgprint("تاريخ البداية يجب أن يسبق تاريخ النهاية");return false;}return true;};
  $root.on("click","[data-scope]",function(){scope=$(this).data("scope");$root.find("[data-scope]").removeClass("is-active");$(this).addClass("is-active");$root.find("[data-company]").toggle(scope==="company");$root.find("[data-hotel]").toggle(scope==="hotel");});
  $root.on("click","[data-action='preview']",()=>{if(!validate())return;$root.find(".wafd-report-preview").show().find("iframe").attr("src",query(false,true));});
  $root.on("click","[data-action='pdf']",()=>{if(validate())window.open(query(true),"_blank","noopener");});
  $root.on("click","[data-action='print']",()=>{if(!validate())return;const win=window.open(query(false),"_blank","noopener");if(!win)frappe.msgprint("اسمح بفتح النوافذ لعرض التقرير وطباعته");});
  $root.on("click","[data-action='share']",async()=>{if(!validate())return;try{const response=await fetch(query(false),{credentials:"same-origin"});if(!response.ok)throw new Error("download");const blob=await response.blob(),file=new File([blob],`WAFD-Delivery-Report-${frappe.datetime.get_today()}.pdf`,{type:"application/pdf"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"تقرير التوصيل WAFD ONE",files:[file]});}else{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);frappe.show_alert({message:"تم تنزيل التقرير ويمكن مشاركته",indicator:"green"});}}catch(error){if(error?.name!=="AbortError")frappe.msgprint("تعذر إنشاء ملف المشاركة. استخدم زر تنزيل PDF.");}});
  frappe.call({method:"wafd_one.delivery_report.get_delivery_report_options",freeze:true}).then(r=>{options=r.message||{};$root.find("#wr-company").html(`<option value="">اختر الشركة أو البعثة</option>${(options.companies||[]).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}`);$root.find("#wr-hotel").html(`<option value="">اختر الفندق</option>${(options.hotels||[]).map(v=>`<option value="${esc(v.name)}">${esc(v.hotel_name_ar||v.hotel_name_en||v.name)}</option>`).join("")}`);});
};
