frappe.pages["wafd-delivery-report"].on_page_load=function(wrapper){
  const ar=(localStorage.getItem("wafd_lang")||"ar")==="ar",tr=(a,e)=>ar?a:e,esc=v=>frappe.utils.escape_html(String(v??""));
  const page=frappe.ui.make_app_page({parent:wrapper,title:tr("تقارير التوصيل","Delivery Reports"),single_column:true}),$root=$(page.body);let data={},mode="all",selectedHotel="";
  const clientOptions=()=>`<option value="">${esc(tr("اختر الشركة أو البعثة أو الجهة","Choose company, mission or entity"))}</option>${(data.companies||[]).map(x=>`<option value="${esc(x.client_name)}">${esc(x.client_name)}</option>`).join("")}`;
  const hotelLabel=x=>ar?(x.hotel_name_ar||x.name):(x.hotel_name_en||x.hotel_name_ar||x.name);
  function reportQuery(){const p=new URLSearchParams({report_mode:mode}),company=$root.find("#wr-company").val(),hotel=selectedHotel,from=$root.find("#wr-from").val(),to=$root.find("#wr-to").val();if(company)p.set("company",company);if(hotel)p.set("hotel",hotel);if(from)p.set("from_date",from);if(to)p.set("to_date",to);return p}
  function pdfUrl(download=0){const p=reportQuery();p.set("download",String(download));return `/api/method/wafd_one.delivery_report.download_delivery_report_pdf?${p.toString()}`}
  function previewUrl(){return `/api/method/wafd_one.delivery_report.preview_delivery_report_html?${reportQuery().toString()}`}
  function validate(){if(mode==="company"&&!$root.find("#wr-company").val()){frappe.msgprint(tr("اختر الشركة أو البعثة أو الجهة","Choose a company, mission or entity"));return false}if(mode==="hotel"&&!selectedHotel){frappe.msgprint(tr("ابحث عن الفندق ثم اختره من النتائج","Search for the hotel and select it from the results"));return false}return true}
  function renderHotelResults(query){const q=String(query||"").trim().toLowerCase(),$results=$root.find("#wr-hotel-results");if(q.length<2){$results.html(`<small>${esc(tr("اكتب حرفين على الأقل للبحث عن الفندق.","Type at least two characters to search."))}</small>`);return}const rows=(data.hotels||[]).filter(x=>`${x.hotel_name_ar||""} ${x.hotel_name_en||""} ${x.name||""}`.toLowerCase().includes(q)).slice(0,10);$results.html(rows.length?rows.map(x=>`<button type="button" data-hotel-choice="${esc(x.name)}">${esc(hotelLabel(x))}${x.hotel_name_en&&ar?`<small>${esc(x.hotel_name_en)}</small>`:""}</button>`).join(""):`<small>${esc(tr("لا توجد نتائج مطابقة.","No matching hotels."))}</small>`)}
  function render(){page.set_title(tr("تقارير التوصيل","Delivery Reports"));$root.attr("dir",ar?"rtl":"ltr").html(`<div class="wafd-delivery-report-page"><section class="wafd-report-hero"><small>WAFD ONE</small><h2>${esc(tr("تقارير تنفيذ وتسليم الوجبات","Meal Delivery Execution Reports"))}</h2></section><section class="wafd-report-panel"><div class="wafd-report-modes"><button data-mode="all" class="${mode==='all'?'is-active':''}">${esc(tr("كامل المدة","Full period"))}</button><button data-mode="company" class="${mode==='company'?'is-active':''}">${esc(tr("حسب الشركة أو البعثة","By company or mission"))}</button><button data-mode="hotel" class="${mode==='hotel'?'is-active':''}">${esc(tr("حسب الفندق","By hotel"))}</button></div><div class="wafd-report-field" data-company ${mode==='company'?'':'style="display:none"'}><span>${esc(tr("الشركة أو البعثة أو الجهة","Company, mission or entity"))}</span><div class="wafd-report-client-row"><select id="wr-company">${clientOptions()}</select><button class="wafd-report-add-client" data-add-client>＋ ${esc(tr("إضافة","Add"))}</button></div></div><div class="wafd-report-field" data-hotel ${mode==='hotel'?'':'style="display:none"'}><span>${esc(tr("بحث الفندق","Hotel search"))}</span><input id="wr-hotel-search" type="search" autocomplete="off" placeholder="${esc(tr("اكتب اسم الفندق بالعربي أو الإنجليزي","Type the hotel name in Arabic or English"))}"><div id="wr-hotel-results" class="wafd-hotel-search-results"><small>${esc(tr("اكتب حرفين على الأقل للبحث عن الفندق.","Type at least two characters to search."))}</small></div></div><div class="wafd-report-fields"><label class="wafd-report-field"><span>${esc(tr("من تاريخ (اختياري)","From date (optional)"))}</span><input id="wr-from" type="date"></label><label class="wafd-report-field"><span>${esc(tr("إلى تاريخ (اختياري)","To date (optional)"))}</span><input id="wr-to" type="date"></label></div><small>${esc(tr("اترك التاريخ فارغاً لعرض كامل المدة.","Leave dates empty for the full period."))}</small><button class="wafd-report-preview-button" data-preview>👁 ${esc(tr("معاينة التقرير","Preview Report"))}</button></section></div>`);}
  function addClient(){const d=new frappe.ui.Dialog({title:tr("إضافة شركة أو بعثة أو جهة","Add Company, Mission or Entity"),fields:[{fieldname:"client_name",fieldtype:"Data",label:tr("الاسم","Name"),reqd:1},{fieldname:"client_type",fieldtype:"Select",label:tr("النوع","Type"),options:[tr("شركة","Company"),tr("بعثة","Mission"),tr("جهة","Entity"),tr("عميل آخر","Other Client")].join("\n"),default:tr("شركة","Company"),reqd:1},{fieldname:"contact_person",fieldtype:"Data",label:tr("مسؤول التواصل (اختياري)","Contact person (optional)")},{fieldname:"mobile",fieldtype:"Data",label:tr("الجوال (اختياري)","Mobile (optional)")}],primary_action_label:tr("حفظ واختيار","Save and select"),primary_action:async v=>{const typeMap={"شركة":"شركة / Company","بعثة":"بعثة / Mission","جهة":"جهة / Entity","عميل آخر":"عميل آخر / Other Client","Company":"شركة / Company","Mission":"بعثة / Mission","Entity":"جهة / Entity","Other Client":"عميل آخر / Other Client"};const r=await frappe.call({method:"wafd_one.delivery_supervisor.add_delivery_client",args:{...v,client_type:typeMap[v.client_type]},freeze:true});if(r.message){data.companies.push(r.message);d.hide();render();mode="company";render();$root.find("#wr-company").val(r.message.client_name);frappe.show_alert({message:tr("تمت الإضافة والاختيار","Added and selected"),indicator:"green"},4)}}});d.show()}
  function fitPreviewFrame(frame){try{const doc=frame.contentDocument,sheet=doc?.querySelector(".sheet");if(!doc||!sheet)return;sheet.style.width="210mm";sheet.style.maxWidth="none";sheet.style.minHeight="297mm";sheet.style.margin="0";sheet.style.position="absolute";sheet.style.top="0";sheet.style.right="0";sheet.style.transform="none";const naturalWidth=sheet.getBoundingClientRect().width||sheet.scrollWidth,available=Math.max(280,frame.clientWidth-8),scale=Math.min(1,available/naturalWidth);sheet.style.transformOrigin="top right";sheet.style.transform=`scale(${scale})`;doc.documentElement.style.overflowX="hidden";doc.body.style.overflowX="hidden";doc.body.style.width="100%";doc.body.style.minHeight=`${Math.ceil(sheet.scrollHeight*scale)}px`}catch(_e){}}
  function printPreviewFrame(frame,pdf){try{const doc=frame.contentDocument,sheet=doc?.querySelector(".sheet");if(!sheet)throw new Error("preview unavailable");["width","maxWidth","minHeight","margin","position","top","right","transform","transformOrigin"].forEach(name=>sheet.style[name]="");doc.documentElement.style.overflowX="";doc.body.style.overflowX="";doc.body.style.width="";doc.body.style.minHeight="";frame.contentWindow.print();setTimeout(()=>fitPreviewFrame(frame),250)}catch(_e){window.open(pdf,"_blank","noopener")}}
  function preview(){if(!validate())return;const htmlUrl=previewUrl(),pdf=pdfUrl(0),$screen=$(`<div class="wafd-report-preview-screen"><div class="wafd-report-toolbar"><button data-back>${esc(tr("رجوع","Back"))}</button><button data-share>${esc(tr("مشاركة","Share"))}</button><button data-print>${esc(tr("طباعة","Print"))}</button></div><iframe class="wafd-report-frame" title="${esc(tr("معاينة التقرير","Report preview"))}" src="${esc(htmlUrl)}"></iframe></div>`).appendTo(document.body),frame=$screen.find("iframe")[0];$(frame).on("load",()=>{fitPreviewFrame(frame);setTimeout(()=>fitPreviewFrame(frame),120)});$screen.on("click","[data-back]",()=>{$screen.remove()});$screen.on("click","[data-print]",()=>printPreviewFrame(frame,pdf));$screen.on("click","[data-share]",async()=>{const response=await fetch(pdfUrl(1),{credentials:"same-origin"}),blob=await response.blob();if(typeof File!=="undefined"){const file=new File([blob],"wafd-delivery-report.pdf",{type:"application/pdf"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:tr("تقرير التوصيل","Delivery Report")});return}}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="wafd-delivery-report.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)})}
  $root.on("click","[data-mode]",function(){mode=$(this).data("mode");if(mode!=="hotel")selectedHotel="";render()});$root.on("click","[data-add-client]",addClient);$root.on("click","[data-preview]",preview);$root.on("input","#wr-hotel-search",function(){selectedHotel="";renderHotelResults(this.value)});$root.on("click","[data-hotel-choice]",function(){selectedHotel=$(this).data("hotel-choice");const row=(data.hotels||[]).find(x=>x.name===selectedHotel);$root.find("#wr-hotel-search").val(row?hotelLabel(row):selectedHotel);$root.find("#wr-hotel-results").html(`<div class="wafd-hotel-selected">✓ ${esc(row?hotelLabel(row):selectedHotel)}</div>`)});
  frappe.call({method:"wafd_one.delivery_report.get_delivery_report_options",freeze:true}).then(r=>{data=r.message||{};render()});
};
