function setupIftarSupervisorPage(wrapper){
 if(!wrapper||wrapper.__ifsup)return;
 const page=frappe.ui.make_app_page({parent:wrapper,title:__('مهام سفر إفطار الصائم'),single_column:true});
 $(wrapper).addClass('wafd-iftar-supervisor-page');
 wrapper.__ifsup={$root:$('<div class="ifs-wrap"></div>').appendTo(page.body),loading:false};
}
frappe.pages['wafd-iftar-supervisor'].on_page_load=function(wrapper){setupIftarSupervisorPage(wrapper);};
(function(){
 const esc=v=>frappe.utils.escape_html(String(v??'')),n=v=>Number(v||0).toLocaleString('en-US');
 const api=(m,args={})=>frappe.call({method:'wafd_one.wafd_one.iftar_stage_portal.'+m,args,freeze:false}).then(r=>r.message);
 const team=(m,args={})=>frappe.call({method:'wafd_one.wafd_one.iftar_team.'+m,args,freeze:false}).then(r=>r.message);
 function cameraField(name,label){return {fieldname:name+'_camera',fieldtype:'HTML',options:`<div class="ifs-camera"><label>${esc(label)} <span class="text-danger">*</span></label><input class="ifs-camera-input" data-camera="${esc(name)}" type="file" accept="image/*" capture="environment"><div class="ifs-camera-hint">التصوير بالكاميرا فقط</div><img class="ifs-camera-preview" data-preview="${esc(name)}" hidden></div>`}}
 function bindCamera(d,name){d.__wafdCamera=d.__wafdCamera||{};const $i=d.$wrapper.find(`[data-camera="${name}"]`),$p=d.$wrapper.find(`[data-preview="${name}"]`);$i.off('.wafdcam').on('change.wafdcam',function(){const file=this.files&&this.files[0];if(!file)return;if(!/^image\//.test(file.type||'')){frappe.msgprint('يجب التقاط صورة من الكاميرا');this.value='';return}const reader=new FileReader();reader.onload=e=>{d.__wafdCamera[name]={data_url:e.target.result,filename:file.name||`${name}.jpg`};$p.attr('src',e.target.result).prop('hidden',false)};reader.readAsDataURL(file)})}
 async function uploadCamera(d,name){const item=d.__wafdCamera&&d.__wafdCamera[name];if(!item){frappe.throw('التقط الصورة المطلوبة من الكاميرا أولاً')}const saved=await api('save_iftar_camera_photo',{image_data:item.data_url,filename:item.filename});if(!saved||!saved.file_url)frappe.throw('تعذر حفظ صورة الكاميرا');return saved.file_url}
 function header(d){return `<div class="ifs-head"><small>WAFD ONE · IFTAR SAIM</small><h1>مهام سفر إفطار الصائم</h1><p>استلام الكمية · أصحاب السفر · حضور المساعدين · التوثيق اليومي</p><p style="margin-top:10px"><b>${esc(d.full_name||d.user)}</b></p></div>`}
 function owners(r){return `<div class="ifs-title"><h2 style="font-size:20px">أصحاب السفر</h2></div>`+(r.table_owners||[]).map(o=>`<div class="ifs-report" data-owner="${esc(o.name)}"><div class="ifs-report-head"><div><b>${esc(o.table_owner_name||'صاحب سفرة')}</b><div class="ifs-muted">${esc(o.mobile_no||'بدون جوال')} · ${esc(o.distribution_point||'')}<br>${n(o.planned_meals)} وجبة · ${n(o.planned_cartons)} كرتون · ${n(o.planned_bread)} خبز · ${n(o.planned_tablecloths)} سفرة</div></div><div>${o.owner_confirmed?'✅ تم التسليم':'بانتظار التسليم'}</div></div>${!o.owner_confirmed&&r.received_meals?`<div class="ifs-report-actions"><button class="ifs-owner-confirm" data-report="${esc(r.name)}">تأكيد التسليم والتوقيع</button></div>`:''}</div>`).join('')}
 function assistants(r){return `<div class="ifs-title"><h2 style="font-size:20px">المساعدون</h2></div>`+((r.assistants||[]).map(a=>`<div class="ifs-report" data-assistant="${esc(a.name)}"><div class="ifs-report-head"><b>${esc(a.assistant_name||'مساعد')}</b><span>${esc(a.attendance_status||'لم يسجل')}</span></div>${!r.report_submitted?`<div class="ifs-report-actions"><button class="ifs-att" data-report="${esc(r.name)}" data-status="حاضر / Present">حاضر</button><button class="ifs-att" data-report="${esc(r.name)}" data-status="غائب / Absent">غائب</button></div>`:''}</div>`).join('')||'<div class="ifs-muted">لا يوجد مساعدون مسجلون.</div>')}
 function card(r){return `<div class="ifs-card" data-report="${esc(r.name)}"><div class="ifs-muted">${esc(r.operation_date||'')} · ${esc(r.project)}</div><h3>${esc(r.project_title||r.project)}</h3><div class="ifs-muted">${esc(r.contracting_entity||'')} · ${esc(r.distribution_site||'')}</div><div class="ifs-grid"><div class="ifs-stat"><b>${n(r.planned_meals)}</b><span>مسند</span></div><div class="ifs-stat"><b>${n(r.received_meals)}</b><span>مستلم من الموقع</span></div><div class="ifs-stat"><b>${(r.table_owners||[]).filter(x=>x.owner_confirmed).length}/${(r.table_owners||[]).length}</b><span>أصحاب السفر</span></div><div class="ifs-stat"><b>${r.manager_approved?'✓':r.report_submitted?'…':'—'}</b><span>اعتماد المدير</span></div></div>${r.received_meals?`<div class="ifs-step"><b>العهدة المستلمة</b><span>${n(r.cartons)} كرتون · ${n(r.bread_bags)} خبز · ${n(r.tablecloths)} سفرة · ${n(r.carts)} عربة · ${n(r.gloves)} قفاز · ${n(r.masks)} كمامة · ${n(r.shoe_covers)} غطاء أرجل</span></div>`:''}${!r.received_meals?'<div class="ifs-step">بانتظار مدير الموقع لتسليم الكمية والعهدة.</div>':owners(r)+assistants(r)}${r.received_meals&&!r.report_submitted?'<button class="ifs-btn ifs-submit-report">إرسال التقرير اليومي لمدير الموقع</button>':''}${r.report_submitted?`<div class="ifs-step ${r.manager_approved?'done':''}">${r.manager_approved?'✓ تم اعتماد التقرير من مدير الموقع':'تم إرسال التقرير وبانتظار اعتماد مدير الموقع'}</div>`:''}</div>`}
 function pending(plans){if(!plans?.length)return '<div class="ifs-empty">لا توجد خطة مشرف مرتبطة بهذا الحساب حتى الآن. اطلب من مدير المشروع إضافتك ضمن المشرفين وأصحاب السفر.</div>';return plans.map(p=>`<div class="ifs-card"><div class="ifs-muted">${esc(p.project)}</div><h3>${esc(p.project_title||p.project)}</h3><div class="ifs-muted">${esc(p.contracting_entity||'')} · ${esc(p.distribution_site||'')}</div><div class="ifs-grid"><div class="ifs-stat"><b>${n(p.assigned_meals)}</b><span>وجبة مسندة</span></div><div class="ifs-stat"><b>${n(p.table_owners_count)}</b><span>أصحاب سفر</span></div></div><div class="ifs-step"><b>تم تسجيلك كمشرف</b><span>بانتظار مدير الموقع إنشاء مهمة اليوم وتسليمك الكمية.</span></div></div>`).join('')}
 function render(w,d){w.__ifsup.data=d;const reports=d.reports||[];w.__ifsup.$root.html(header(d)+`<div class="ifs-title"><h2>تكليفاتي اليومية</h2><span>${reports.length}</span></div>`+(reports.length?reports.map(card).join(''):pending(d.plans||[])));bind(w)}
 function bind(w){const $r=w.__ifsup.$root;$r.off('.ifsup');
  $r.on('click.ifsup','.ifs-owner-confirm',function(){const report=$(this).data('report'),owner=$(this).closest('[data-owner]').data('owner'),rr=w.__ifsup.data.reports.find(x=>x.name===report),o=rr.table_owners.find(x=>x.name===owner);const d=new frappe.ui.Dialog({title:'تأكيد التسليم لصاحب السفرة',fields:[{fieldname:'delivered_meals',fieldtype:'Int',label:'عدد الوجبات المسلمة',default:o.planned_meals,reqd:1},{fieldname:'delivered_bread',fieldtype:'Int',label:'عدد الخبز المسلم',default:o.planned_bread},{fieldname:'delivered_tablecloths',fieldtype:'Int',label:'عدد السفر المسلمة',default:o.planned_tablecloths},cameraField('delivery_photo','صورة التسليم'),{fieldname:'recipient_signature',fieldtype:'Signature',label:'توقيع صاحب السفرة',reqd:1},{fieldname:'notes',fieldtype:'Small Text',label:'ملاحظة'}],primary_action_label:'تأكيد التسليم',primary_action:async v=>{const delivery_photo=await uploadCamera(d,'delivery_photo');await team('confirm_owner_handover',{report_name:report,owner_row_name:owner,...v,delivery_photo});d.hide();frappe.show_alert({message:'تم حفظ التسليم والتوقيع والوقت',indicator:'green'});loadSup(w)}});d.show();bindCamera(d,'delivery_photo')});
  $r.on('click.ifsup','.ifs-att',function(){const report=$(this).data('report'),assistant=$(this).closest('[data-assistant]').data('assistant'),status=$(this).data('status');if(status==='حاضر / Present'){team('mark_assistant_attendance',{report_name:report,assistant_row_name:assistant,status}).then(()=>{frappe.show_alert({message:'تم تسجيل الحضور والوقت',indicator:'green'});loadSup(w)});return}const d=new frappe.ui.Dialog({title:'تسجيل الغياب',fields:[{fieldname:'absence_reason',fieldtype:'Small Text',label:'سبب الغياب',reqd:1}],primary_action_label:'تأكيد الغياب',primary_action:async v=>{await team('mark_assistant_attendance',{report_name:report,assistant_row_name:assistant,status,absence_reason:v.absence_reason});d.hide();loadSup(w)}});d.show()});
  $r.on('click.ifsup','.ifs-submit-report',function(){const report=$(this).closest('[data-report]').data('report');const rr=w.__ifsup.data.reports.find(x=>x.name===report);const received=Number(rr.received_meals||0);const d=new frappe.ui.Dialog({title:'التقرير اليومي للمشرف',fields:[{fieldname:'distributed_meals',fieldtype:'Int',label:'الموزع',default:received,reqd:1},{fieldname:'surplus_meals',fieldtype:'Int',label:'الفائض المرتجع للإعاشة',default:0},{fieldname:'preservation_meals',fieldtype:'Int',label:'المسلم لجمعية حفظ النعمة',default:0},{fieldname:'waste_meals',fieldtype:'Int',label:'التالف',default:0},{fieldname:'tables_spread_completed',fieldtype:'Check',label:'تم فرش السفر',default:1},{fieldname:'distribution_completed',fieldtype:'Check',label:'تم توزيع الوجبات',default:1},{fieldname:'cleanup_completed',fieldtype:'Check',label:'تم رفع السفر والنفايات',default:1},cameraField('distribution_photo','صورة التوزيع'),cameraField('closeout_photo','صورة رفع السفر'),cameraField('preservation_receipt_photo','صورة استلام حفظ النعمة (عند وجود كمية)'),{fieldname:'preservation_receiver_signature',fieldtype:'Signature',label:'توقيع مستلم حفظ النعمة (عند وجود كمية)'},{fieldname:'supervisor_notes',fieldtype:'Small Text',label:'ملاحظات المشرف'}],primary_action_label:'إرسال التقرير',primary_action:async v=>{const distribution_photo=await uploadCamera(d,'distribution_photo'),closeout_photo=await uploadCamera(d,'closeout_photo');let preservation_receipt_photo=null;if(Number(v.preservation_meals||0)>0)preservation_receipt_photo=await uploadCamera(d,'preservation_receipt_photo');await team('submit_supervisor_report',{report_name:report,...v,distribution_photo,closeout_photo,preservation_receipt_photo});d.hide();frappe.show_alert({message:'تم إرسال التقرير لمدير الموقع',indicator:'green'});loadSup(w)}});d.show();bindCamera(d,'distribution_photo');bindCamera(d,'closeout_photo');bindCamera(d,'preservation_receipt_photo')});
 }
 async function loadSup(w){if(!w?.__ifsup||w.__ifsup.loading)return;w.__ifsup.loading=true;w.__ifsup.$root.html('<div class="ifs-empty">جاري تحميل مهام المشرف…</div>');try{render(w,await api('get_supervisor_portal_data'))}catch(e){console.error('WAFD Iftar Supervisor load failed',e);w.__ifsup.$root.html(`<div class="ifs-empty"><b>تعذر تحميل مهام المشرف</b><br>${esc(e.message||e)}<br><button class="ifs-btn ifs-retry" style="margin-top:14px">إعادة المحاولة</button></div>`);w.__ifsup.$root.off('click.ifsretry').on('click.ifsretry','.ifs-retry',()=>loadSup(w))}finally{w.__ifsup.loading=false}}
 frappe.pages['wafd-iftar-supervisor'].on_page_show=function(wrapper){setupIftarSupervisorPage(wrapper);loadSup(wrapper)};
})();
