frappe.pages['wafd-iftar-supervisor'].on_page_load=function(wrapper){const page=frappe.ui.make_app_page({parent:wrapper,title:__('مهام سفر إفطار الصائم'),single_column:true});$(wrapper).addClass('wafd-iftar-supervisor-page');wrapper.__ifsup={$root:$('<div class="ifs-wrap"></div>').appendTo(page.body),loading:false}}
(function(){
 const esc=v=>frappe.utils.escape_html(String(v??'')),n=v=>Number(v||0).toLocaleString('en-US');
 const api=(m,args={})=>frappe.call({method:'wafd_one.wafd_one.iftar_stage_portal.'+m,args,freeze:false}).then(r=>r.message);
 const team=(m,args={})=>frappe.call({method:'wafd_one.wafd_one.iftar_team.'+m,args,freeze:false}).then(r=>r.message);
 function header(d){return `<div class="ifs-head"><small>WAFD ONE · IFTAR SAIM</small><h1>مهام سفر إفطار الصائم</h1><p>استلام الكمية · أصحاب السفر · حضور المساعدين · التوثيق اليومي</p><p style="margin-top:10px"><b>${esc(d.full_name||d.user)}</b></p></div>`}
 function owners(r){return `<div class="ifs-title"><h2 style="font-size:20px">أصحاب السفر</h2></div>`+(r.table_owners||[]).map(o=>`<div class="ifs-report" data-owner="${esc(o.name)}"><div class="ifs-report-head"><div><b>${esc(o.table_owner_name||'صاحب سفرة')}</b><div class="ifs-muted">${esc(o.distribution_point||'')} · ${n(o.planned_meals)} وجبة</div></div><div>${o.owner_confirmed?'✅ تم التسليم':'بانتظار التسليم'}</div></div>${!o.owner_confirmed&&r.received_meals?`<div class="ifs-report-actions"><button class="ifs-owner-confirm" data-report="${esc(r.name)}" data-qty="${n(o.planned_meals)}">تأكيد التسليم لصاحب السفرة</button></div>`:''}</div>`).join('')}
 function assistants(r){return `<div class="ifs-title"><h2 style="font-size:20px">المساعدون</h2></div>`+((r.assistants||[]).map(a=>`<div class="ifs-report" data-assistant="${esc(a.name)}"><div class="ifs-report-head"><b>${esc(a.assistant_name||'مساعد')}</b><span>${esc(a.attendance_status||'لم يسجل')}</span></div>${!r.report_submitted?`<div class="ifs-report-actions"><button class="ifs-att" data-report="${esc(r.name)}" data-status="حاضر / Present">حاضر</button><button class="ifs-att" data-report="${esc(r.name)}" data-status="غائب / Absent">غائب</button></div>`:''}</div>`).join('')||'<div class="ifs-muted">لا يوجد مساعدون مسجلون.</div>')}
 function card(r){return `<div class="ifs-card" data-report="${esc(r.name)}"><div class="ifs-muted">${esc(r.operation_date||'')} · ${esc(r.project)}</div><h3>${esc(r.project_title||r.project)}</h3><div class="ifs-muted">${esc(r.contracting_entity||'')} · ${esc(r.distribution_site||'')}</div><div class="ifs-grid"><div class="ifs-stat"><b>${n(r.planned_meals)}</b><span>مسند</span></div><div class="ifs-stat"><b>${n(r.received_meals)}</b><span>مستلم من الموقع</span></div><div class="ifs-stat"><b>${(r.table_owners||[]).filter(x=>x.owner_confirmed).length}/${(r.table_owners||[]).length}</b><span>أصحاب السفر</span></div><div class="ifs-stat"><b>${r.manager_approved?'✓':r.report_submitted?'…':'—'}</b><span>اعتماد المدير</span></div></div>${!r.received_meals?'<div class="ifs-step">بانتظار مدير الموقع لتسليم الكمية والعهدة.</div>':owners(r)+assistants(r)}${r.received_meals&&!r.report_submitted?'<button class="ifs-btn ifs-submit-report">إرسال التقرير اليومي لمدير الموقع</button>':''}${r.report_submitted?`<div class="ifs-step ${r.manager_approved?'done':''}">${r.manager_approved?'✓ تم اعتماد التقرير من مدير الموقع':'تم إرسال التقرير وبانتظار اعتماد مدير الموقع'}</div>`:''}</div>`}
 function pending(plans){if(!plans?.length)return '<div class="ifs-empty">لا توجد خطة مشرف مرتبطة بهذا الحساب حتى الآن. اطلب من مدير الموقع إضافتك ضمن المشرفين وأصحاب السفر.</div>';return plans.map(p=>`<div class="ifs-card"><div class="ifs-muted">${esc(p.project)}</div><h3>${esc(p.project_title||p.project)}</h3><div class="ifs-muted">${esc(p.contracting_entity||'')} · ${esc(p.distribution_site||'')}</div><div class="ifs-grid"><div class="ifs-stat"><b>${n(p.assigned_meals)}</b><span>وجبة مسندة</span></div><div class="ifs-stat"><b>${n(p.table_owners_count)}</b><span>أصحاب سفر</span></div></div><div class="ifs-step"><b>تم تسجيلك كمشرف</b><span>بانتظار مدير الموقع إنشاء مهمة اليوم وتسليمك الكمية.</span></div></div>`).join('')}
 function render(w,d){w.__ifsup.data=d;const reports=d.reports||[];w.__ifsup.$root.html(header(d)+`<div class="ifs-title"><h2>تكليفاتي اليومية</h2><span>${reports.length}</span></div>`+(reports.length?reports.map(card).join(''):pending(d.plans||[])));bind(w)}
 function bind(w){const $r=w.__ifsup.$root;$r.off('.ifsup');
  $r.on('click.ifsup','.ifs-owner-confirm',function(){const report=$(this).data('report'),owner=$(this).closest('[data-owner]').data('owner'),qty=Number($(this).data('qty'));const d=new frappe.ui.Dialog({title:'تأكيد التسليم لصاحب السفرة',fields:[{fieldname:'delivered_meals',fieldtype:'Int',label:'عدد الوجبات المسلمة',default:qty,reqd:1},{fieldname:'notes',fieldtype:'Small Text',label:'ملاحظة'}],primary_action_label:'تأكيد التسليم',primary_action:async v=>{await team('confirm_owner_handover',{report_name:report,owner_row_name:owner,delivered_meals:v.delivered_meals,notes:v.notes||''});d.hide();frappe.show_alert({message:'تم تأكيد التسليم',indicator:'green'});loadSup(w)}});d.show()});
  $r.on('click.ifsup','.ifs-att',async function(){await team('mark_assistant_attendance',{report_name:$(this).data('report'),assistant_row_name:$(this).closest('[data-assistant]').data('assistant'),status:$(this).data('status')});frappe.show_alert({message:'تم تسجيل الحضور',indicator:'green'});loadSup(w)});
  $r.on('click.ifsup','.ifs-submit-report',function(){const report=$(this).closest('[data-report]').data('report');const rr=w.__ifsup.data.reports.find(x=>x.name===report);const received=Number(rr.received_meals||0);const d=new frappe.ui.Dialog({title:'التقرير اليومي للمشرف',fields:[{fieldname:'distributed_meals',fieldtype:'Int',label:'الموزع',default:received,reqd:1},{fieldname:'surplus_meals',fieldtype:'Int',label:'الفائض المرتجع',default:0},{fieldname:'preservation_meals',fieldtype:'Int',label:'حفظ النعمة',default:0},{fieldname:'waste_meals',fieldtype:'Int',label:'التالف',default:0},{fieldname:'tables_spread_completed',fieldtype:'Check',label:'تم فرش السفر',default:1},{fieldname:'distribution_completed',fieldtype:'Check',label:'تم توزيع الوجبات',default:1},{fieldname:'cleanup_completed',fieldtype:'Check',label:'تم رفع السفر والنفايات',default:1},{fieldname:'distribution_photo',fieldtype:'Attach Image',label:'صورة التوزيع',reqd:1},{fieldname:'closeout_photo',fieldtype:'Attach Image',label:'صورة رفع السفر',reqd:1},{fieldname:'media_links',fieldtype:'Long Text',label:'روابط صور أو فيديو إضافية'}],primary_action_label:'إرسال التقرير',primary_action:async v=>{await team('submit_supervisor_report',{report_name:report,...v});d.hide();frappe.show_alert({message:'تم إرسال التقرير لمدير الموقع',indicator:'green'});loadSup(w)}});d.show()});
 }
 async function loadSup(w){if(!w?.__ifsup||w.__ifsup.loading)return;w.__ifsup.loading=true;w.__ifsup.$root.html('<div class="ifs-empty">جاري تحميل مهام المشرف…</div>');try{render(w,await api('get_supervisor_portal_data'))}catch(e){console.error('WAFD Iftar Supervisor load failed',e);w.__ifsup.$root.html(`<div class="ifs-empty"><b>تعذر تحميل مهام المشرف</b><br>${esc(e.message||e)}<br><button class="ifs-btn ifs-retry" style="margin-top:14px">إعادة المحاولة</button></div>`);w.__ifsup.$root.off('click.ifsretry').on('click.ifsretry','.ifs-retry',()=>loadSup(w))}finally{w.__ifsup.loading=false}}
 frappe.pages['wafd-iftar-supervisor'].on_page_show=function(wrapper){loadSup(wrapper)};
})();
