frappe.pages["wafd-iftar-team"].on_page_load = function(wrapper) {
  frappe.ui.make_app_page({parent:wrapper,title:__("فريق إفطار الصائم"),single_column:true});
  const $root=$(wrapper).find('.layout-main-section').html(`<div class="ift-wrap"><section class="ift-hero"><h2>تشغيل مشروع إفطار الصائم</h2><p class="ift-subtitle"></p><div class="ift-controls"><input type="date" class="form-control ift-date"><select class="form-control ift-project"><option value="">جميع المشاريع</option></select><button class="btn btn-light ift-refresh">تحديث</button></div></section><div class="ift-body"></div></div>`);
  $root.find('.ift-date').val(frappe.datetime.get_today());
  let data={projects:[],operations:[],reports:[],mode:''};
  const esc=v=>frappe.utils.escape_html(String(v||'')), num=v=>frappe.format(Number(v||0),{fieldtype:'Int'});
  const call=(method,args={})=>frappe.call({method:`wafd_one.wafd_one.iftar_team.${method}`,args,freeze:true});
  const upload=(name,label)=>({fieldname:name,fieldtype:'Attach Image',label,reqd:1});
  function dialog(title,fields,label,action){const d=new frappe.ui.Dialog({title,fields,primary_action_label:label,primary_action:async v=>{await action(v);d.hide();await load();}});d.show();}

  function shortcuts(){
    if(data.mode==='administration') return `<div class="ift-shortcuts"><button class="ift-shortcut" data-page="wafd-iftar-wizard"><b>إنشاء العقد والخطة</b><span>المدة والأعداد والأسعار والرواتب والتكاليف</span></button><button class="ift-shortcut" data-list="WAFD Iftar Supervisor Plan"><b>خطة الفريق الشهرية</b><span>المشرفون وأصحاب السفر والمساعدون</span></button><button class="ift-shortcut" data-page="wafd-iftar-operations"><b>لوحة الإدارة</b><span>المؤشرات والتقرير الرسمي</span></button></div>`;
    if(data.mode==='delivery') return `<div class="ift-shortcuts"><button class="ift-shortcut" data-page="wafd-delivery-supervisor"><b>جدول التوصيل الحالي</b><span>السائق والمركبة والموقع والوجبات والخبز والعهدة</span></button></div><div class="alert alert-info">لا ينشئ النظام رحلة إفطار جديدة؛ يعتمد نفس جدول التوصيل الظاهر للسائقين.</div>`;
    return '';
  }
  function plans(){
    if(!['administration','project_manager'].includes(data.mode)) return '';
    return `<h3 class="ift-title">الخطة والعقد والفريق</h3><div class="ift-grid">${(data.projects||[]).map(p=>`<article class="ift-card"><span class="ift-badge">${Number(p.docstatus)===1?'الخطة معتمدة':'مسودة بانتظار الاعتماد'}</span><h4>${esc(p.project_title)}</h4><div class="ift-row"><span>الوجبات اليومية</span><b>${num(p.daily_meals)}</b></div><div class="ift-row"><span>الموقع والجهة</span><b>${esc(p.distribution_site)} · ${esc(p.contracting_entity)}</b></div><div class="ift-row"><span>المشرفون / أصحاب السفر / المساعدون</span><b>${num(p.supervisors_count)} / ${num(p.table_owners_count)} / ${num(p.assistants_count)}</b></div><div class="ift-row"><span>الموزع على المشرفين</span><b>${num(p.assigned_meals)} من ${num(p.daily_meals)}</b></div>${data.mode==='administration'?`<button class="btn btn-default" data-assign="${esc(p.name)}">إسناد الفريق الأساسي</button><button class="btn btn-default" data-list="WAFD Iftar Supervisor Plan">خطط المشرفين</button>${Number(p.docstatus)===0?`<button class="btn btn-primary" data-activate="${esc(p.name)}">اعتماد الخطة وبدء التشغيل</button>`:''}`:''}</article>`).join('')}</div>`;
  }
  function actions(o){
    if(data.mode==='administration') return o.site_report_approved&&!o.daily_report_sent?`<button class="btn btn-success" data-send="${esc(o.name)}">اعتماد وإرسال التقرير للجهة</button>`:`<button class="btn btn-default" data-open-op="${esc(o.name)}">فتح التفاصيل</button>`;
    if(data.mode==='project_manager') return `<button class="btn btn-default" data-open-op="${esc(o.name)}">متابعة التفاصيل</button>`;
    if(data.mode==='kitchen') return !o.kitchen_started?`<button class="btn btn-primary" data-start-kitchen="${esc(o.name)}">بدء عمل ${num(o.planned_meals)} وجبة</button>`:!o.kitchen_ready_approved?`<button class="btn btn-primary" data-kitchen="${esc(o.name)}" data-ready="${o.kitchen_ready_meals||0}">تسجيل الجاهز واعتماده</button>`:`<button class="btn btn-success" disabled>تم اعتماد الجاهزية</button>`;
    if(data.mode==='delivery') return `<button class="btn btn-primary" data-page="wafd-delivery-supervisor">فتح جدول التوصيل الحالي</button>${o.kitchen_ready_approved&&!o.delivery_plan_approved?`<button class="btn btn-success" data-dispatch="${esc(o.name)}">اعتماد السيارات والتحميل</button>`:''}`;
    if(data.mode==='site') return `${o.authority_inspection_approved?`<button class="btn btn-primary" data-generate="${esc(o.name)}">تجهيز تكليفات المشرفين</button>`:''}${!o.site_receipt_approved&&Number(o.delivery_verified_meals)>0?`<button class="btn btn-primary" data-site-receipt="${esc(o.name)}" data-arrived="${Number(o.delivery_verified_meals)||0}">اعتماد استلام الموقع</button>`:''}${o.site_receipt_approved&&!o.authority_inspection_approved?`<button class="btn btn-primary" data-inspection="${esc(o.name)}">اعتماد فحص مفتش التغذية</button>`:''}${o.authority_inspection_approved&&!o.site_report_approved?`<button class="btn btn-success" data-finalize="${esc(o.name)}">اعتماد تقرير مدير الموقع</button>`:''}`;
    return '';
  }
  function operations(){
    if(!data.operations.length) return `<div class="ift-empty">لا يوجد تشغيل معتمد في هذا التاريخ. ${data.mode==='administration'?'أكمل الفريق وخطط المشرفين ثم اضغط اعتماد الخطة وبدء التشغيل.':''}</div>`;
    return `<div class="ift-grid">${data.operations.map(o=>{const stages=(o.stages||[]).map(s=>`<div class="ift-row"><span>${s.done?'✓':'○'} ${esc(s.label)}</span><b>${s.time?frappe.datetime.str_to_user(s.time):'بانتظار المرحلة'}</b></div>`).join('');const trips=(o.deliveries||[]).map(t=>`<div class="ift-delivery"><b>${esc(t.driver||'السائق غير محدد')} · ${esc(t.vehicle||'المركبة غير محددة')}</b><br>${esc(t.destination_name)} — ${num(t.quantity)} وجبة — ${num(t.iftar_bread_quantity)} خبز ${t.iftar_loading_photo?'✓ صورة':''}${data.mode==='delivery'&&!o.delivery_plan_approved?`<br><button class="btn btn-xs btn-default" data-trip="${esc(t.name)}" data-bread="${t.iftar_bread_quantity||0}">الخبز والعهدة وصورة التحميل</button>`:''}</div>`).join('');return `<article class="ift-card"><span class="ift-badge">${esc(o.status)}</span><h4>${esc(o.project_title)}</h4><div class="ift-row"><span>المخطط</span><b>${num(o.planned_meals)} وجبة · ${num(o.cartons)} كرتون</b></div><div class="ift-row"><span>الإنتاج / التغليف / التحميل</span><b>${num(o.produced_meals)} / ${num(o.packaged_meals)} / ${num(o.loaded_meals)}</b></div><div class="ift-row"><span>الوصول المثبت</span><b>${num(o.delivery_verified_meals)} · ${num(o.delivery_proof_count)} إثبات</b></div><h5>تسلسل الاعتمادات</h5>${stages}${o.kitchen_shortage_reported?`<div class="ift-warning"><b>نقص مواد</b><br>${esc(o.kitchen_shortage_notes)}</div>`:''}${trips}${actions(o)}</article>`;}).join('')}</div>`;
  }
  function reports(){
    if(!['administration','project_manager','site','supervisor'].includes(data.mode)) return '';
    return `<h3 class="ift-title">تقارير المشرفين</h3>${data.reports.length?`<div class="ift-grid">${data.reports.map(r=>{const owners=(r.owners||[]).map(x=>`<div class="ift-row"><span>${esc(x.table_owner_name)} — ${esc(x.distribution_point)}<br><small>${esc(x.mobile_no)}</small></span><b>${num(x.delivered_meals)} / ${num(x.planned_meals)} ${x.owner_confirmed?'✓':''}</b>${data.mode==='supervisor'&&!x.owner_confirmed&&r.received_meals?`<button class="btn btn-xs btn-primary" data-owner="${esc(r.name)}" data-owner-row="${esc(x.name)}" data-planned="${x.planned_meals||0}">اعتماد التسليم</button>`:''}</div>`).join('');const assistants=(r.assistants||[]).map(x=>`<div class="ift-row"><span>${esc(x.assistant_name)} — ${esc(x.mobile_no)}</span><b>${esc(x.attendance_status)}</b>${data.mode==='supervisor'&&x.attendance_status==='لم يسجل / Not Marked'?`<button class="btn btn-xs btn-success" data-assistant="${esc(r.name)}" data-assistant-row="${esc(x.name)}" data-status="حاضر / Present">حاضر</button><button class="btn btn-xs btn-default" data-assistant="${esc(r.name)}" data-assistant-row="${esc(x.name)}" data-status="غائب / Absent">غائب</button>`:''}</div>`).join('');return `<article class="ift-card"><span class="ift-badge">${r.manager_approved?'معتمد':r.report_submitted?'بانتظار مدير الموقع':'قيد العمل'}</span><h4>${esc(r.supervisor_name)}</h4><div class="ift-row"><span>المسند / المستلم</span><b>${num(r.planned_meals)} / ${num(r.received_meals)}</b></div><h5>المساعدون</h5>${assistants||'لا يوجد'}<h5>أصحاب السفر والمواقع</h5>${owners}${data.mode==='site'&&!r.received_meals?`<button class="btn btn-primary" data-receive="${esc(r.name)}" data-planned="${r.planned_meals||0}">تسليم الوجبات والعهدة</button>`:''}${data.mode==='supervisor'&&r.received_meals&&!r.report_submitted?`<button class="btn btn-success" data-submit-report="${esc(r.name)}" data-received="${r.received_meals||0}">إغلاق الموقع وإرسال التقرير</button>`:''}${data.mode==='site'&&r.report_submitted&&!r.manager_approved?`<button class="btn btn-success" data-approve="${esc(r.name)}">اعتماد تقرير المشرف</button>`:''}<button class="btn btn-default" data-report="${esc(r.name)}">التفاصيل والصور</button></article>`;}).join('')}</div>`:`<div class="ift-empty">لم تنشأ تقارير المشرفين لهذا اليوم بعد.</div>`}`;
  }
  function render(){const labels={administration:'شاشة الإدارة — العقد والخطة والتقرير النهائي',project_manager:'شاشة مدير المشروع — متابعة جميع المراحل',kitchen:'شاشة مشرف المطبخ',delivery:'شاشة مشرف التوصيل',site:'شاشة مدير الموقع',supervisor:'شاشة المشرف الميداني'};$root.find('.ift-subtitle').text(labels[data.mode]||'واجهة الموظف حسب المهمة');const total=data.operations.reduce((s,x)=>s+Number(x.planned_meals||0),0),ready=data.operations.reduce((s,x)=>s+Number(x.kitchen_ready_meals||0),0);$root.find('.ift-body').html(`${shortcuts()}${plans()}<div class="ift-kpis"><div class="ift-kpi"><span>المشاريع اليوم</span><strong>${data.operations.length}</strong></div><div class="ift-kpi"><span>الوجبات</span><strong>${num(total)}</strong></div><div class="ift-kpi"><span>الجاهز</span><strong>${num(ready)}</strong></div><div class="ift-kpi"><span>تقارير المشرفين</span><strong>${data.reports.length}</strong></div></div><h3 class="ift-title">تشغيل اليوم</h3>${operations()}${reports()}`);}
  async function load(){const res=await call('get_team_dashboard',{date:$root.find('.ift-date').val(),project:$root.find('.ift-project').val()||null});data=res.message||{};const current=$root.find('.ift-project').val();$root.find('.ift-project').html(`<option value="">جميع المشاريع</option>${data.projects.map(p=>`<option value="${esc(p.name)}">${esc(p.project_title)} — ${esc(p.distribution_site)}</option>`).join('')}`).val(current||'');render();}

  $root.on('click','[data-page]',function(){frappe.set_route($(this).data('page'));}).on('click','[data-list]',function(){frappe.set_route('List',$(this).data('list'));}).on('click','[data-open-op]',function(){frappe.set_route('Form','WAFD Iftar Daily Operation',$(this).data('open-op'));}).on('click','[data-report]',function(){frappe.set_route('Form','WAFD Iftar Supervisor Daily Report',$(this).data('report'));});
  $root.on('click','[data-activate]',async function(){await call('approve_project_plan',{project_name:$(this).data('activate')});frappe.show_alert({message:'تم اعتماد الخطة وإنشاء التشغيل اليومي',indicator:'green'},5);load();});
  $root.on('click','[data-start-kitchen]',async function(){await call('start_kitchen',{operation_name:$(this).data('start-kitchen')});load();});
  $root.on('click','[data-kitchen]',function(){const name=$(this).data('kitchen');dialog('جاهزية المطبخ والنواقص',[{fieldname:'ready_meals',fieldtype:'Int',label:'العدد الجاهز',reqd:1,default:$(this).data('ready')},{fieldname:'shortage_reported',fieldtype:'Check',label:'يوجد نقص مواد'},{fieldname:'shortage_notes',fieldtype:'Small Text',label:'بيان المواد الناقصة',depends_on:'shortage_reported'},{fieldname:'approve',fieldtype:'Check',label:'اعتماد انتهاء الإنتاج والتغليف',default:1}],'حفظ واعتماد',v=>call('update_kitchen',{operation_name:name,...v}));});
  $root.on('click','[data-dispatch]',async function(){await call('approve_delivery_dispatch',{operation_name:$(this).data('dispatch')});frappe.show_alert({message:'تم اعتماد السيارات والتحميل',indicator:'green'},5);load();});
  $root.on('click','[data-trip]',function(){const name=$(this).data('trip');dialog('عهدة السيارة وصورة التحميل',[{fieldname:'bread_quantity',fieldtype:'Int',label:'أكياس الخبز',reqd:1,default:$(this).data('bread')},{fieldname:'tablecloths',fieldtype:'Int',label:'السفر'},{fieldname:'waste_bags',fieldtype:'Int',label:'أكياس النفايات'},{fieldname:'gloves',fieldtype:'Int',label:'القفازات'},{fieldname:'shoe_covers',fieldtype:'Int',label:'غطاء الأرجل'},upload('loading_photo','صورة التحميل'),{fieldname:'notes',fieldtype:'Small Text',label:'ملاحظات'}],'حفظ بيانات السيارة',v=>call('update_delivery_allocation',{trip_name:name,...v}));});
  $root.on('click','[data-site-receipt]',function(){const name=$(this).data('site-receipt');dialog('اعتماد استلام مدير الموقع',[{fieldname:'received_meals',fieldtype:'Int',label:'العدد المستلم',reqd:1,default:$(this).data('arrived')}],'اعتماد الاستلام',v=>call('approve_site_receipt',{operation_name:name,...v}));});
  $root.on('click','[data-inspection]',function(){const name=$(this).data('inspection');dialog('فحص مشرف التغذية من الجهة',[{fieldname:'supervisor_name',fieldtype:'Data',label:'اسم مفتش التغذية',reqd:1},{fieldname:'yogurt_checked',fieldtype:'Check',label:'تم فحص الزبادي'},{fieldname:'bread_checked',fieldtype:'Check',label:'تم فحص الخبز'},{fieldname:'dates_checked',fieldtype:'Check',label:'تم فحص التمر'},{fieldname:'expiry_checked',fieldtype:'Check',label:'تم فحص الصلاحية'},upload('photo','صورة الفحص'),{fieldname:'notes',fieldtype:'Small Text',label:'الملاحظات'}],'اعتماد الفحص',v=>call('approve_authority_inspection',{operation_name:name,...v}));});
  $root.on('click','[data-generate]',async function(){await call('ensure_supervisor_reports',{operation_name:$(this).data('generate')});load();});
  $root.on('click','[data-receive]',function(){const name=$(this).data('receive');dialog('تسليم الوجبات والعهدة للمشرف',[{fieldname:'received_meals',fieldtype:'Int',label:'عدد الوجبات',reqd:1,default:$(this).data('planned')},{fieldname:'tablecloths',fieldtype:'Int',label:'السفر'},{fieldname:'bread_bags',fieldtype:'Int',label:'أكياس الخبز'},{fieldname:'waste_bags',fieldtype:'Int',label:'أكياس النفايات'},{fieldname:'gloves',fieldtype:'Int',label:'القفازات'},{fieldname:'shoe_covers',fieldtype:'Int',label:'غطاء الأرجل'},upload('handover_photo','صورة التسليم للمشرف')],'اعتماد التسليم',v=>call('receive_for_supervisor',{report_name:name,...v}));});
  $root.on('click','[data-owner]',function(){const report=$(this).data('owner'),owner=$(this).data('owner-row');dialog('تسليم صاحب السفرة',[{fieldname:'delivered_meals',fieldtype:'Int',label:'عدد الوجبات المسلمة',reqd:1,default:$(this).data('planned')},{fieldname:'notes',fieldtype:'Small Text',label:'ملاحظات'}],'اعتماد التسليم',v=>call('confirm_owner_handover',{report_name:report,owner_row_name:owner,...v}));});
  $root.on('click','[data-assistant]',async function(){await call('mark_assistant_attendance',{report_name:$(this).data('assistant'),assistant_row_name:$(this).data('assistant-row'),status:$(this).data('status')});load();});
  $root.on('click','[data-submit-report]',function(){const name=$(this).data('submit-report');dialog('إغلاق الموقع وإرسال التقرير',[{fieldname:'distributed_meals',fieldtype:'Int',label:'الموزع',reqd:1,default:$(this).data('received')},{fieldname:'surplus_meals',fieldtype:'Int',label:'الفائض المرتجع'},{fieldname:'preservation_meals',fieldtype:'Int',label:'جمعية حفظ النعمة'},{fieldname:'waste_meals',fieldtype:'Int',label:'التالف'},{fieldname:'tables_spread_completed',fieldtype:'Check',label:'تم فرش السفر'},{fieldname:'distribution_completed',fieldtype:'Check',label:'تم التوزيع'},{fieldname:'cleanup_completed',fieldtype:'Check',label:'تم رفع السفر والنفايات'},upload('distribution_photo','صورة التوزيع'),upload('closeout_photo','صورة رفع السفر')],'إرسال لمدير الموقع',v=>call('submit_supervisor_report',{report_name:name,...v}));});
  $root.on('click','[data-approve]',async function(){await call('approve_supervisor_report',{report_name:$(this).data('approve')});load();}).on('click','[data-finalize]',async function(){await call('finalize_daily_report',{operation_name:$(this).data('finalize')});frappe.show_alert({message:'تم إرسال تقرير مدير الموقع للإدارة',indicator:'green'},5);load();});
  $root.on('click','[data-send]',function(){const name=$(this).data('send');dialog('اعتماد الإدارة وإرسال التقرير',[{fieldname:'recipient',fieldtype:'Data',label:'رئاسة شؤون الحرمين أو الجهة المتعاقدة',reqd:1}],'اعتماد وإرسال',v=>call('send_authority_report',{operation_name:name,...v}));});
  $root.on('click','[data-assign]',function(){const projectName=$(this).data('assign'),p=data.projects.find(x=>x.name===projectName)||{};dialog('إسناد الفريق الأساسي',[{fieldname:'project_manager_user',fieldtype:'Link',options:'User',label:'مدير المشروع',default:p.project_manager_user||''},{fieldname:'kitchen_supervisor_user',fieldtype:'Link',options:'User',label:'مشرف المطبخ',default:p.kitchen_supervisor_user||''},{fieldname:'delivery_supervisor_user',fieldtype:'Link',options:'User',label:'مشرف التوصيل',default:p.delivery_supervisor_user||''},{fieldname:'site_manager_user',fieldtype:'Link',options:'User',label:'مدير الموقع',default:p.site_manager_user||''}],'حفظ الفريق',v=>call('assign_project_team',{project_name:projectName,...v}));});
  $root.find('.ift-refresh').on('click',load);$root.find('.ift-date,.ift-project').on('change',load);load();
};
